'use strict';

/**
 * INTERVIEW PREPARATION — PDF RENDERER
 *
 * One schema-driven renderer produces both documents the module offers:
 *
 *   mode 'blank'      the fillable template. Every question carries a real
 *                     AcroForm field, so it opens in Preview, Acrobat, Edge
 *                     or Chrome and is typed into like any other form.
 *   mode 'populated'  a stored interview. The same layout, the same fields,
 *                     with the portal's answers already in them — so the
 *                     downloaded document is still editable, and a reviewer
 *                     can annotate it without going back to the portal.
 *
 * ── The rule that shapes everything here ───────────────────────────────────
 * NO ANSWER IS EVER CLIPPED, SHRUNK OR TRUNCATED. The source template gave
 * every question a fixed box, which is why it could not survive a real
 * interview: a three-paragraph answer simply disappeared below the fold. This
 * renderer measures each answer first and sizes its field to the text, and
 * when an answer is taller than the page has left, it SPLITS — the remainder
 * continues in a "Response continued" field on the next page. A six-page
 * template therefore prints as six, eight or fourteen pages depending on what
 * was written, and that is the correct behaviour.
 *
 * Two mechanisms make "never clipped" a guarantee rather than an intention:
 *
 *   1. Measurement is deliberately PESSIMISTIC. Lines are wrapped against
 *      MEASURE_INSET (8pt of side padding), while pdf-lib lays the field's
 *      appearance out against 3.4pt. Wrapping against a narrower column than
 *      the renderer will actually use means pdf-lib can only ever produce the
 *      same number of lines or fewer — never more, which is the direction
 *      that would clip. interview-pdf.test.js proves this against pdf-lib's
 *      own layoutMultilineText rather than trusting the argument.
 *   2. Every field is built one full line taller than its measured text
 *      (SPARE_LINES), so even an unforeseen disagreement about a break point
 *      has somewhere to land — and, in a blank or partly-filled form, the
 *      person typing has room for one more line before the box is full.
 *
 * Beyond that, the field's /V value carries the answer's own text — the
 * renderer stores what the interviewer typed, not a re-flowed copy of it —
 * so the document is recoverable by reading the form rather than by scraping
 * a page. The test suite reads it back and compares it to the input character
 * for character, including the deliberately enormous one.
 *
 * The single exception is a token too wide for the column to hold at all (a
 * pasted URL, a run of underscores). pdf-lib does not break those; it lets
 * them run off the edge. softenLongTokens() inserts the break pdf-lib will
 * not, before anything is measured, so a pathological token wraps instead of
 * escaping the page.
 *
 * ── Fonts, and why user text is transliterated ─────────────────────────────
 * The standard PDF fonts encode WinAnsi (CP1252). An interviewer pasting a
 * candidate's answer can easily bring in a character outside it — a Greek
 * letter, a CJK name, an arrow, an emoji — and pdf-lib THROWS on those rather
 * than dropping them, which would turn "one odd character" into "no document
 * at all". toWinAnsi() therefore transliterates the common cases (→ becomes
 * ->, ≈ becomes ~, a curly quote stays a curly quote because CP1252 has it)
 * and substitutes anything genuinely unrepresentable. Embedding a Unicode
 * font would be the fuller answer; it needs a licensed font binary and the
 * fontkit dependency, and is noted in docs rather than assumed here.
 *
 * ── Branding ───────────────────────────────────────────────────────────────
 * Colours, the teal band, the section bars and the footer are measured from
 * Opal Therapy's own Occupational Therapist Interview Template so a document
 * generated by the portal and one printed from the template look like the
 * same document, because they are.
 */

const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');

const tpl = require('./interview-templates');

// ─────────────────────────────────────────────────────────────────────────────
//  Page geometry (A4) and the palette sampled from the Opal template
// ─────────────────────────────────────────────────────────────────────────────

const PAGE_W = 595.28;
const PAGE_H = 841.89;

const MARGIN_L = 51;
const MARGIN_R = 51;
const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;   // 493.28

const BAND_H = 18;                 // the teal strip across the head of every page
const CONTENT_TOP = PAGE_H - 58;   // first baseline area below the band
const CONTENT_BOTTOM = 64;         // nothing is drawn below this; footer lives under it

const FOOTER_RULE_Y = 50;
const FOOTER_TEXT_Y = 36;

const TEAL   = rgb(0.173, 0.478, 0.482); // #2C7A7B
const NAVY   = rgb(0.090, 0.196, 0.302); // #17324D
const SLATE  = rgb(0.176, 0.216, 0.282); // #2D3748
const MUTED  = rgb(0.443, 0.502, 0.588); // #718096
const BORDER = rgb(0.796, 0.835, 0.878); // #CBD5E0
const PANEL  = rgb(0.957, 0.965, 0.973); // #F4F6F8
const WHITE  = rgb(1, 1, 1);

// Type scale
const SIZE_TITLE    = 21;
const SIZE_INTRO    = 8.5;
const SIZE_SECTION  = 12;
const SIZE_QUESTION = 9.5;
const SIZE_GUIDE    = 7.5;
const SIZE_ANSWER   = 9;
const SIZE_LINE_FIELD = 9.5;
const SIZE_LABEL    = 7.5;
const SIZE_FOOTER   = 7.5;

/**
 * Leading inside an answer field.
 *
 * pdf-lib lays a text field's appearance out at `font.heightAtSize(size) * 1.2`
 * — 9.99pt for 9pt Helvetica. Matching it means the box is sized to what the
 * renderer will actually draw instead of to a guess, so a full page of answer
 * is a full page rather than three-quarters of one. Rounded up, never down.
 */
const LINE_ANSWER   = 10;
const LINE_QUESTION = 12;
const LINE_GUIDE    = 9.5;

const SECTION_BAR_H = 26;
const FIELD_VPAD    = 4;     // vertical padding inside an answer field
/**
 * How much narrower than the field this layout measures its lines.
 *
 * pdf-lib wraps against `width - (borderWidth + 1) * 2` ≈ width - 3.4. Wrapping
 * against a column 8pt narrower means every line this code counts is a line
 * pdf-lib can also fit, so its own layout can only ever come out the same
 * length or shorter — never longer, which is the direction that would clip.
 */
const MEASURE_INSET = 8;
const SPARE_LINES   = 1;     // headroom every field carries
const MIN_SPLIT_LINES = 3;   // never strand fewer than this at a page break

const CHECK_BOX = 10.5;

// ─────────────────────────────────────────────────────────────────────────────
//  WinAnsi safety
// ─────────────────────────────────────────────────────────────────────────────

/** The CP1252-only code points, i.e. the 0x80–0x9F block's real characters. */
const CP1252_HIGH = [
  0x20AC, 0x201A, 0x0192, 0x201E, 0x2026, 0x2020, 0x2021, 0x02C6, 0x2030,
  0x0160, 0x2039, 0x0152, 0x017D, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022,
  0x2013, 0x2014, 0x02DC, 0x2122, 0x0161, 0x203A, 0x0153, 0x017E, 0x0178,
];
const ENCODABLE = new Set(CP1252_HIGH);
for (let c = 0x20; c <= 0x7E; c += 1) ENCODABLE.add(c);
for (let c = 0xA0; c <= 0xFF; c += 1) ENCODABLE.add(c);

/**
 * Characters worth spelling out rather than replacing, because they carry
 * meaning an interviewer actually typed. Everything absent from this map and
 * from ENCODABLE becomes '?'.
 *
 * The Latin Extended-A block matters more than the symbols: a candidate called
 * Sarka, Lukasz, Ngatai or Nguyen should read as their name on the printed
 * record rather than as a row of question marks. CP1252 already carries the
 * whole of Latin-1 (e-acute, u-umlaut, n-tilde, c-cedilla, o-slash, a-ring)
 * untouched, so only the Extended-A letters need mapping.
 *
 * Scripts with no Latin form at all — CJK, Arabic, Hebrew, Cyrillic, Thai —
 * cannot be represented by a standard PDF font and become '?'. Fixing that
 * needs an embedded Unicode font (a licensed font binary plus the fontkit
 * dependency); it is recorded in docs/INTERVIEW_PREPARATION.md as a known
 * limitation rather than silently assumed away here.
 */
const TRANSLITERATE = {
  // Symbols and arrows
  '→': '->', '←': '<-', '↔': '<->', '⇒': '=>', '⇐': '<=',
  '≤': '<=', '≥': '>=', '≠': '!=', '≈': '~',
  '×': 'x', '−': '-', '÷': '/', '∞': 'infinity', '√': 'sqrt',
  '✓': '[yes]', '✔': '[yes]', '✗': '[no]', '✘': '[no]',
  '☑': '[yes]', '☐': '[ ]',
  '●': '•', '▪': '•', '◦': '•', '‣': '•', '⁃': '•',
  '─': '-', '━': '-', '➔': '->',
  // Spaces and invisibles
  ' ': ' ', ' ': ' ', ' ': ' ', ' ': ' ', ' ': ' ',
  '​': '', '﻿': '', ' ': '\n', ' ': '\n',
  // Latin Extended-A: the accented letters CP1252 leaves out
  'Ā': 'A', 'ā': 'a', 'Ă': 'A', 'ă': 'a', 'Ą': 'A', 'ą': 'a',
  'Ć': 'C', 'ć': 'c', 'Ĉ': 'C', 'ĉ': 'c', 'Ċ': 'C', 'ċ': 'c',
  'Č': 'C', 'č': 'c', 'Ď': 'D', 'ď': 'd', 'Đ': 'D', 'đ': 'd',
  'Ē': 'E', 'ē': 'e', 'Ĕ': 'E', 'ĕ': 'e', 'Ė': 'E', 'ė': 'e',
  'Ę': 'E', 'ę': 'e', 'Ě': 'E', 'ě': 'e',
  'Ĝ': 'G', 'ĝ': 'g', 'Ğ': 'G', 'ğ': 'g', 'Ġ': 'G', 'ġ': 'g',
  'Ģ': 'G', 'ģ': 'g', 'Ĥ': 'H', 'ĥ': 'h', 'Ħ': 'H', 'ħ': 'h',
  'Ĩ': 'I', 'ĩ': 'i', 'Ī': 'I', 'ī': 'i', 'Ĭ': 'I', 'ĭ': 'i',
  'Į': 'I', 'į': 'i', 'İ': 'I', 'ı': 'i',
  'Ĵ': 'J', 'ĵ': 'j', 'Ķ': 'K', 'ķ': 'k',
  'Ĺ': 'L', 'ĺ': 'l', 'Ļ': 'L', 'ļ': 'l', 'Ľ': 'L', 'ľ': 'l',
  'Ł': 'L', 'ł': 'l',
  'Ń': 'N', 'ń': 'n', 'Ņ': 'N', 'ņ': 'n', 'Ň': 'N', 'ň': 'n',
  'Ŋ': 'N', 'ŋ': 'n',
  'Ō': 'O', 'ō': 'o', 'Ŏ': 'O', 'ŏ': 'o', 'Ő': 'O', 'ő': 'o',
  'Ŕ': 'R', 'ŕ': 'r', 'Ŗ': 'R', 'ŗ': 'r', 'Ř': 'R', 'ř': 'r',
  'Ś': 'S', 'ś': 's', 'Ŝ': 'S', 'ŝ': 's', 'Ş': 'S', 'ş': 's',
  'Ţ': 'T', 'ţ': 't', 'Ť': 'T', 'ť': 't', 'Ŧ': 'T', 'ŧ': 't',
  'Ũ': 'U', 'ũ': 'u', 'Ū': 'U', 'ū': 'u', 'Ŭ': 'U', 'ŭ': 'u',
  'Ů': 'U', 'ů': 'u', 'Ű': 'U', 'ű': 'u', 'Ų': 'U', 'ų': 'u',
  'Ŵ': 'W', 'ŵ': 'w', 'Ŷ': 'Y', 'ŷ': 'y',
  'Ź': 'Z', 'ź': 'z', 'Ż': 'Z', 'ż': 'z',
  'Ơ': 'O', 'ơ': 'o', 'Ư': 'U', 'ư': 'u',
  'Ə': 'E', 'ə': 'e',
};

/**
 * Make a string safe for a standard PDF font without ever throwing.
 * Line endings are normalised here too, so callers only ever deal with '\n'.
 */
function toWinAnsi(value) {
  const s = String(value === null || value === undefined ? '' : value)
    .replace(/\r\n?/g, '\n')
    .replace(/\t/g, '    ');
  let out = '';
  for (const ch of s) {
    if (ch === '\n') { out += ch; continue; }
    const cp = ch.codePointAt(0);
    if (ENCODABLE.has(cp)) { out += ch; continue; }
    if (Object.prototype.hasOwnProperty.call(TRANSLITERATE, ch)) { out += TRANSLITERATE[ch]; continue; }
    // Control characters vanish; anything else leaves a visible placeholder so
    // a reader can see that something was there.
    out += (cp < 0x20 || cp === 0x7F) ? '' : '?';
  }
  return out;
}

/** AcroForm field names are a flat namespace; '.' would create a hierarchy. */
function fieldName(key) {
  return String(key || 'field').replace(/[^A-Za-z0-9_-]/g, '_').slice(0, 90);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Text measurement
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Insert the line breaks pdf-lib will not.
 *
 * pdf-lib's splitOutLines only ever breaks at spaces: a single token wider
 * than the column is emitted whole and runs off the edge of the field. This
 * pass finds those tokens before anything is measured and breaks them at the
 * last character that fits, so wrapping downstream — mine and pdf-lib's alike
 * — has somewhere legal to break. Ordinary prose passes through untouched,
 * which is why the stored answer keeps the interviewer's own line structure.
 */
function softenLongTokens(text, font, size, width) {
  const widthOf = (s) => font.widthOfTextAtSize(s, size);
  // Cheap exit: nothing in this string is long enough to matter.
  if (!/\S{20,}/.test(text)) return text;

  return text.replace(/\S+/g, (token) => {
    if (widthOf(token) <= width) return token;
    let rest = token;
    let out = '';
    while (widthOf(rest) > width) {
      let cut = 1;
      while (cut < rest.length && widthOf(rest.slice(0, cut + 1)) <= width) cut += 1;
      out += `${rest.slice(0, cut)}\n`;
      rest = rest.slice(cut);
    }
    return out + rest;
  });
}

/**
 * Wrap `text` to `width`, honouring existing newlines.
 *
 * Returns `{ source, lines }` where `source` is the WinAnsi-safe, long-token-
 * softened string every offset refers to, and each line is
 * `{ text, start, end }` indexing into it. The offsets are what make a split
 * answer keep the interviewer's own words: a chunk's field value is
 * `source.slice(firstLine.start, lastLine.end)`, which is the ORIGINAL text of
 * those lines — paragraph breaks intact, soft wraps still soft — rather than a
 * re-flowed reconstruction.
 *
 * An empty input yields one empty line, because a blank answer still occupies
 * a row in the layout.
 */
function wrapMeasured(text, font, size, width) {
  const source = softenLongTokens(toWinAnsi(text), font, size, width);
  const widthOf = (s) => font.widthOfTextAtSize(s, size);
  const lines = [];

  let offset = 0;
  const paragraphs = source.split('\n');

  paragraphs.forEach((paragraph, pIndex) => {
    const paraStart = offset;
    offset += paragraph.length + (pIndex < paragraphs.length - 1 ? 1 : 0);

    if (paragraph === '') { lines.push({ text: '', start: paraStart, end: paraStart }); return; }

    const tokens = [];
    const re = /\s+|\S+/g;
    let m;
    while ((m = re.exec(paragraph)) !== null) {
      tokens.push({ text: m[0], start: paraStart + m.index, end: paraStart + m.index + m[0].length });
    }

    let current = '';
    let start = -1;
    let end = -1;
    const flush = () => {
      if (start < 0) return;
      lines.push({ text: current.replace(/\s+$/, ''), start, end });
      current = ''; start = -1; end = -1;
    };

    for (const token of tokens) {
      const isSpace = /^\s+$/.test(token.text);
      if (start < 0 && isSpace) {
        // Leading whitespace on a wrapped line is dropped, as pdf-lib drops it.
        continue;
      }
      const candidate = current + token.text;
      if (widthOf(candidate) <= width || start < 0) {
        if (start < 0) start = token.start;
        current = candidate;
        end = token.end;
        continue;
      }
      flush();
      if (isSpace) continue;
      start = token.start; current = token.text; end = token.end;
    }
    flush();
    // A paragraph of nothing but whitespace still holds a line.
    if (!lines.length || lines[lines.length - 1].end < paraStart) {
      lines.push({ text: '', start: paraStart, end: paraStart + paragraph.length });
    }
  });

  return { source, lines: lines.length ? lines : [{ text: '', start: 0, end: 0 }] };
}

/** The line strings alone — the shape most callers and the tests want. */
function wrapText(text, font, size, width) {
  return wrapMeasured(text, font, size, width).lines.map((l) => l.text);
}

// ─────────────────────────────────────────────────────────────────────────────
//  The flowing document
// ─────────────────────────────────────────────────────────────────────────────

class Flow {
  constructor(pdf, fonts, meta) {
    this.pdf = pdf;
    this.form = pdf.getForm();
    this.font = fonts.regular;
    this.bold = fonts.bold;
    this.italic = fonts.italic;
    this.meta = meta;              // { footer }
    this.pages = [];
    this.page = null;
    this.y = 0;
    this.usedNames = new Set();
    this.newPage();
  }

  newPage() {
    const page = this.pdf.addPage([PAGE_W, PAGE_H]);
    page.drawRectangle({ x: 0, y: PAGE_H - BAND_H, width: PAGE_W, height: BAND_H, color: TEAL });
    this.pages.push(page);
    this.page = page;
    this.y = CONTENT_TOP;
    return page;
  }

  /** Room left on the current page for content. */
  get available() {
    return this.y - CONTENT_BOTTOM;
  }

  /** Ensure `height` of room, starting a page if not. Returns true if it broke. */
  ensure(height) {
    if (this.available >= height) return false;
    this.newPage();
    return true;
  }

  move(dy) {
    this.y -= dy;
  }

  /** A unique AcroForm name, so a split answer's parts never collide. */
  uniqueName(base) {
    let name = fieldName(base);
    let n = 2;
    while (this.usedNames.has(name)) { name = `${fieldName(base)}_${n}`; n += 1; }
    this.usedNames.add(name);
    return name;
  }

  text(value, opts = {}) {
    const size = opts.size || SIZE_QUESTION;
    const font = opts.bold ? this.bold : (opts.italic ? this.italic : this.font);
    const colour = opts.colour || SLATE;
    const lineHeight = opts.lineHeight || (size * 1.28);
    const width = opts.width || CONTENT_W;
    const x = opts.x === undefined ? MARGIN_L : opts.x;
    const lines = wrapText(value, font, size, width);

    for (const line of lines) {
      this.ensure(lineHeight);
      this.page.drawText(line, { x, y: this.y - size, size, font, color: colour });
      this.move(lineHeight);
    }
    return lines.length;
  }

  /** Height a text block would take, without drawing it. */
  measureText(value, opts = {}) {
    const size = opts.size || SIZE_QUESTION;
    const font = opts.bold ? this.bold : (opts.italic ? this.italic : this.font);
    const lineHeight = opts.lineHeight || (size * 1.28);
    const width = opts.width || CONTENT_W;
    return wrapText(value, font, size, width).length * lineHeight;
  }

  /** Paint the footer rule, caption and page number on every page. */
  finish() {
    const total = this.pages.length;
    this.pages.forEach((page, i) => {
      page.drawLine({
        start: { x: MARGIN_L, y: FOOTER_RULE_Y },
        end: { x: PAGE_W - MARGIN_R, y: FOOTER_RULE_Y },
        thickness: 0.6,
        color: BORDER,
      });
      page.drawText(toWinAnsi(this.meta.footer), {
        x: MARGIN_L, y: FOOTER_TEXT_Y, size: SIZE_FOOTER, font: this.font, color: NAVY,
      });
      const label = `Page ${i + 1} of ${total}`;
      const w = this.font.widthOfTextAtSize(label, SIZE_FOOTER);
      page.drawText(label, {
        x: PAGE_W - MARGIN_R - w, y: FOOTER_TEXT_Y, size: SIZE_FOOTER, font: this.font, color: MUTED,
      });
    });
  }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Field primitives
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Place one multiline answer field.
 *
 * `lines` is already wrapped and already pessimistic (see MEASURE_INSET), so
 * the box below is sized from a line count pdf-lib cannot exceed. The field's
 * value is the FULL chunk text — the appearance is what the box shows, /V is
 * what the document holds.
 */
function drawAnswerField(flow, { name, lines, value, x, width, height }) {
  const field = flow.form.createTextField(name);
  field.enableMultiline();
  if (value) field.setText(toWinAnsi(value));
  field.addToPage(flow.page, {
    x,
    y: flow.y - height,
    width,
    height,
    borderColor: BORDER,
    borderWidth: 0.7,
    backgroundColor: WHITE,
    textColor: SLATE,
    font: flow.font,
  });
  // AFTER addToPage: the /DA entry a font size is written into does not exist
  // until the widget does. The size then fixes the appearance at the one this
  // layout was measured against — left on auto, pdf-lib would shrink the text
  // to fit its own idea of the box and the document would drift out of step
  // with the portal. The final updateFieldAppearances() redraws at this size.
  field.setFontSize(SIZE_ANSWER);
  void lines;
  return field;
}

function drawLineField(flow, { name, value, x, y, width, height }) {
  const field = flow.form.createTextField(name);
  if (value) field.setText(toWinAnsi(value));
  field.addToPage(flow.page, {
    x, y, width, height,
    borderColor: BORDER,
    borderWidth: 0.7,
    backgroundColor: WHITE,
    textColor: SLATE,
    font: flow.font,
  });
  field.setFontSize(SIZE_LINE_FIELD);
  return field;
}

function drawCheckBox(flow, { name, checked, x, y, size = CHECK_BOX }) {
  const box = flow.form.createCheckBox(name);
  box.addToPage(flow.page, {
    x, y, width: size, height: size,
    borderColor: BORDER, borderWidth: 0.9, backgroundColor: WHITE,
  });
  if (checked) box.check();
  return box;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Question renderers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A narrative answer, split across as many pages as it needs.
 *
 * Pagination rules, in the order they are applied:
 *   - the question label and at least MIN_SPLIT_LINES of its answer stay
 *     together, so a question is never orphaned at the foot of a page;
 *   - a chunk that will not fit starts a new page rather than being squeezed;
 *   - a continuation is announced ("Response continued"), so a reader always
 *     knows they are still inside the previous question.
 */
function renderNarrative(flow, question, value, mode) {
  const label = question.label || '';
  const guidance = question.guidance || '';
  const answer = mode === 'blank' ? '' : String(value === undefined || value === null ? '' : value);

  const labelH = flow.measureText(label, { size: SIZE_QUESTION, lineHeight: LINE_QUESTION });
  const guideH = guidance
    ? flow.measureText(guidance, { size: SIZE_GUIDE, lineHeight: LINE_GUIDE }) + 2
    : 0;

  const measureWidth = CONTENT_W - MEASURE_INSET;
  const measured = answer
    ? wrapMeasured(answer, flow.font, SIZE_ANSWER, measureWidth)
    : { source: '', lines: [] };
  let lines = measured.lines;

  // A blank (or unanswered) field still needs a box worth writing in: the
  // template's own suggested height, never fewer than three lines.
  const blankLines = Math.max(3, Number(question.rows) || 3);
  if (!lines.length) lines = new Array(blankLines).fill(null);

  const heightFor = (count) => (count + SPARE_LINES) * LINE_ANSWER + FIELD_VPAD * 2;

  // Keep the question with a meaningful piece of its answer.
  const headKeep = labelH + guideH + 6 + heightFor(Math.min(lines.length, MIN_SPLIT_LINES));
  flow.ensure(headKeep);

  flow.text(label, { size: SIZE_QUESTION, lineHeight: LINE_QUESTION, colour: SLATE });
  if (guidance) {
    flow.move(1);
    flow.text(guidance, { size: SIZE_GUIDE, lineHeight: LINE_GUIDE, colour: MUTED, italic: true });
  }
  flow.move(4);

  let remaining = lines;
  let part = 0;

  while (remaining.length) {
    // How many lines can this page still take?
    const room = flow.available;
    let capacity = Math.floor((room - FIELD_VPAD * 2) / LINE_ANSWER) - SPARE_LINES;

    if (capacity < Math.min(remaining.length, MIN_SPLIT_LINES)) {
      flow.newPage();
      if (part > 0) {
        flow.text('Response continued', {
          size: SIZE_GUIDE, lineHeight: LINE_GUIDE, colour: MUTED, italic: true,
        });
        flow.move(3);
      }
      capacity = Math.floor((flow.available - FIELD_VPAD * 2) / LINE_ANSWER) - SPARE_LINES;
    }

    const take = Math.min(remaining.length, Math.max(capacity, 1));
    const chunk = remaining.slice(0, take);
    remaining = remaining.slice(take);

    const height = heightFor(chunk.length);
    // The chunk's OWN text, sliced out of the measured source — not the
    // measured lines rejoined. Soft wraps stay soft, paragraph breaks stay
    // where the interviewer put them, and the field holds what they typed.
    const chunkText = answer && chunk[0]
      ? measured.source.slice(chunk[0].start, chunk[chunk.length - 1].end)
      : '';
    drawAnswerField(flow, {
      name: flow.uniqueName(part === 0 ? question.key : `${question.key}__cont${part + 1}`),
      lines: chunk,
      value: chunkText,
      x: MARGIN_L,
      width: CONTENT_W,
      height,
    });
    flow.move(height + 10);
    part += 1;

    if (remaining.length) {
      flow.newPage();
      flow.text('Response continued', {
        size: SIZE_GUIDE, lineHeight: LINE_GUIDE, colour: MUTED, italic: true,
      });
      flow.move(3);
    }
  }
}

function renderCheckboxes(flow, question, value, mode) {
  const options = question.options || [];
  const chosen = new Set(mode === 'blank' ? [] : (Array.isArray(value) ? value : []));

  const cols = 2;
  const rows = Math.ceil(options.length / cols);
  const colW = CONTENT_W / cols;
  const rowH = 22;

  const labelH = flow.measureText(question.label || '', { size: SIZE_QUESTION, lineHeight: LINE_QUESTION });
  flow.ensure(labelH + 6 + rows * rowH);

  flow.text(question.label || '', { size: SIZE_QUESTION, lineHeight: LINE_QUESTION, colour: SLATE });
  flow.move(6);

  const top = flow.y;
  options.forEach((opt, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = MARGIN_L + col * colW;
    const y = top - row * rowH - CHECK_BOX;
    drawCheckBox(flow, {
      name: flow.uniqueName(`${question.key}__${opt.key}`),
      checked: chosen.has(opt.key),
      x, y,
    });
    flow.page.drawText(toWinAnsi(opt.label), {
      x: x + CHECK_BOX + 8,
      y: y + 1.5,
      size: SIZE_QUESTION,
      font: flow.font,
      color: SLATE,
    });
  });
  flow.move(rows * rowH + 6);
}

/**
 * A single-choice question. Rendered as one AcroForm radio group so the
 * options stay mutually exclusive in a PDF reader too — a set of independent
 * checkboxes would let somebody tick "Progress" and "Do not progress" at once,
 * which is precisely the contradiction the portal's own control prevents.
 */
function renderChoice(flow, question, value, mode) {
  const options = question.options || [];
  const selected = mode === 'blank' ? null : (value && value.option) || null;
  const detail = mode === 'blank' ? '' : ((value && value.detail) || '');
  const detailOption = options.find((o) => o.detail);

  const inline = options.length <= 3 && options.every((o) => (o.label || '').length <= 16);
  const rowH = 22;
  const rows = inline ? 1 : options.length;

  const labelH = flow.measureText(question.label || '', { size: SIZE_QUESTION, lineHeight: LINE_QUESTION });
  const detailH = detailOption ? 46 : 0;
  flow.ensure(labelH + 8 + rows * rowH + detailH);

  flow.text(question.label || '', {
    size: question.emphasis ? SIZE_QUESTION + 1 : SIZE_QUESTION,
    lineHeight: LINE_QUESTION,
    colour: question.emphasis ? NAVY : SLATE,
    bold: !!question.emphasis,
  });
  flow.move(6);

  const group = flow.form.createRadioGroup(flow.uniqueName(question.key));
  const top = flow.y;
  options.forEach((opt, i) => {
    const x = inline ? MARGIN_L + i * (CONTENT_W / options.length) : MARGIN_L;
    const y = inline ? top - CHECK_BOX : top - i * rowH - CHECK_BOX;
    group.addOptionToPage(opt.key, flow.page, {
      x, y, width: CHECK_BOX, height: CHECK_BOX,
      borderColor: BORDER, borderWidth: 0.9, backgroundColor: WHITE,
    });
    flow.page.drawText(toWinAnsi(opt.label), {
      x: x + CHECK_BOX + 8, y: y + 1.5, size: SIZE_QUESTION, font: flow.font, color: SLATE,
    });
  });
  if (selected && options.some((o) => o.key === selected)) {
    try { group.select(selected); } catch (_) { /* an unknown key simply stays unselected */ }
  }
  flow.move(rows * rowH + 4);

  if (detailOption) {
    const h = 30;
    flow.ensure(h + 14);
    flow.page.drawText(toWinAnsi(detailOption.detailLabel || 'Details'), {
      x: MARGIN_L, y: flow.y - SIZE_LABEL, size: SIZE_LABEL, font: flow.font, color: MUTED,
    });
    flow.move(SIZE_LABEL + 4);
    drawLineField(flow, {
      name: flow.uniqueName(`${question.key}__detail`),
      value: detail,
      x: MARGIN_L, y: flow.y - h, width: CONTENT_W, height: h,
    });
    flow.move(h + 8);
  }
}

/**
 * The rating grid. Every score is a labelled radio option inside a row-scoped
 * group, so "Communication — 3" is unambiguous on paper, in a screen reader
 * and in a PDF reader, and no row can hold two scores at once.
 */
function renderRatings(flow, question, value, mode) {
  const scale = question.scale || tpl.RATING_SCALE;
  const rows = question.rows || [];
  const scores = mode === 'blank' ? {} : (value && typeof value === 'object' ? value : {});

  const rowH = 23;
  const guideH = question.guide ? 20 : 0;
  const headH = 18;
  flow.ensure(headH + rows.length * rowH + guideH + 10);

  // Column header: the numbers, once, above the grid.
  const labelColW = 190;
  const gridX = MARGIN_L + labelColW;
  const stepW = (CONTENT_W - labelColW) / scale.length;

  scale.forEach((n, i) => {
    const label = String(n);
    const w = flow.bold.widthOfTextAtSize(label, SIZE_LABEL);
    flow.page.drawText(label, {
      x: gridX + i * stepW + (CHECK_BOX - w) / 2 + 1,
      y: flow.y - SIZE_LABEL,
      size: SIZE_LABEL, font: flow.bold, color: MUTED,
    });
  });
  flow.move(headH);

  rows.forEach((row) => {
    flow.ensure(rowH);
    const y = flow.y - CHECK_BOX;
    flow.page.drawText(toWinAnsi(row.label), {
      x: MARGIN_L, y: y + 1.5, size: SIZE_QUESTION, font: flow.font, color: SLATE,
    });
    const group = flow.form.createRadioGroup(flow.uniqueName(`${question.key}__${row.key}`));
    scale.forEach((n, i) => {
      group.addOptionToPage(`${n}`, flow.page, {
        x: gridX + i * stepW, y, width: CHECK_BOX, height: CHECK_BOX,
        borderColor: BORDER, borderWidth: 0.9, backgroundColor: WHITE,
      });
    });
    const chosen = Number(scores[row.key]);
    if (Number.isFinite(chosen) && scale.includes(chosen)) {
      try { group.select(String(chosen)); } catch (_) { /* leave unselected */ }
    }
    flow.move(rowH);
  });

  if (question.guide) {
    flow.move(4);
    flow.text(`Rating guide: ${question.guide}`, {
      size: SIZE_GUIDE, lineHeight: LINE_GUIDE, colour: MUTED, italic: true,
    });
  }
  flow.move(6);
}

function renderQuestion(flow, question, responses, mode) {
  const value = (responses || {})[question.key];
  switch (question.type) {
    case 'checkboxes': return renderCheckboxes(flow, question, value, mode);
    case 'choice':     return renderChoice(flow, question, value, mode);
    case 'ratings':    return renderRatings(flow, question, value, mode);
    case 'text':
    case 'date':
    case 'longtext':
    default:           return renderNarrative(flow, question, value, mode);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Document furniture
// ─────────────────────────────────────────────────────────────────────────────

function renderTitleBlock(flow, template) {
  flow.text(template.documentTitle || template.name, {
    size: SIZE_TITLE, lineHeight: SIZE_TITLE * 1.2, colour: NAVY,
  });
  flow.move(6);
  if (template.summary) {
    flow.text(template.summary, { size: SIZE_INTRO, lineHeight: SIZE_INTRO * 1.4, colour: MUTED });
  }
  flow.move(14);
}

/**
 * The candidate panel — the grey block at the head of the source template.
 * In 'populated' mode the values are already in the fields but the fields stay
 * editable, because an interviewer correcting a spelling should not have to
 * return to the portal.
 */
function renderCandidatePanel(flow, header, mode) {
  const cellH = 24;
  const panelH = 2 * (SIZE_LABEL + 4 + cellH) + 30;
  flow.ensure(panelH);

  const top = flow.y;
  flow.page.drawRectangle({
    x: MARGIN_L - 12, y: top - panelH, width: CONTENT_W + 24, height: panelH, color: PANEL,
  });

  const colW = (CONTENT_W - 20) / 2;
  const cells = [
    { key: 'candidate_name', label: 'Candidate name', value: header.candidateName },
    { key: 'interview_date', label: 'Interview date', value: header.interviewDate },
    { key: 'interviewers', label: 'Interviewer(s)', value: header.interviewers },
    { key: 'role_position', label: 'Role / position', value: header.position },
  ];

  cells.forEach((cell, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = MARGIN_L + col * (colW + 20);
    const labelY = top - 15 - row * (SIZE_LABEL + 6 + cellH);
    flow.page.drawText(toWinAnsi(cell.label), {
      x, y: labelY, size: SIZE_LABEL, font: flow.font, color: MUTED,
    });
    drawLineField(flow, {
      name: flow.uniqueName(cell.key),
      value: mode === 'blank' ? '' : cell.value,
      x, y: labelY - 5 - cellH, width: colW, height: cellH,
    });
  });

  flow.move(panelH + 16);
}

function renderSectionBar(flow, section) {
  // A heading alone at the foot of a page is a broken document; keep it with
  // at least the first 40pt of whatever follows.
  flow.ensure(SECTION_BAR_H + 46);
  const y = flow.y - SECTION_BAR_H;
  flow.page.drawRectangle({
    x: MARGIN_L - 12, y, width: CONTENT_W + 24, height: SECTION_BAR_H, color: TEAL,
  });
  flow.page.drawText(toWinAnsi(`${section.number}. ${section.title}`), {
    x: MARGIN_L + 4, y: y + (SECTION_BAR_H - SIZE_SECTION) / 2 + 1.5,
    size: SIZE_SECTION, font: flow.font, color: WHITE,
  });
  flow.move(SECTION_BAR_H + 14);
}

function renderSignoff(flow, fields, responses, mode, header) {
  const cellH = 26;
  flow.ensure(SIZE_LABEL + 6 + cellH + 10);
  const colW = (CONTENT_W - 20) / 2;
  const top = flow.y;
  fields.forEach((f, i) => {
    const x = MARGIN_L + i * (colW + 20);
    flow.page.drawText(toWinAnsi(f.label), {
      x, y: top - SIZE_LABEL, size: SIZE_LABEL, font: flow.font, color: MUTED,
    });
    const typed = (responses || {})[f.key];
    const value = mode === 'blank'
      ? ''
      // An untyped sign-off falls back to the record's own interviewer/date
      // rather than printing blank; anything typed always wins.
      : (typed || (f.fallback && header ? header[f.fallback] : '') || '');
    drawLineField(flow, {
      name: flow.uniqueName(f.key),
      value,
      x, y: top - SIZE_LABEL - 6 - cellH, width: colW, height: cellH,
    });
  });
  flow.move(SIZE_LABEL + 6 + cellH + 10);
}

/**
 * The provenance strip on a populated document: who conducted it, what state
 * it is in, and whether it was edited after being declared complete. A printed
 * recruitment record that does not say this is not a record.
 */
function renderProvenance(flow, header) {
  const bits = [];
  if (header.status) bits.push(`Status: ${header.status}`);
  if (header.createdByName) bits.push(`Created by ${header.createdByName}`);
  if (header.completedAtText) bits.push(`Completed ${header.completedAtText}`);
  if (header.postCompletionEdits) {
    bits.push(`Edited after completion (${header.postCompletionEdits}${header.postCompletionEdits === 1 ? ' time' : ' times'})`);
  }
  if (header.generatedAtText) bits.push(`Generated ${header.generatedAtText}`);
  if (!bits.length) return;
  flow.move(4);
  flow.text(bits.join('  ·  '), { size: SIZE_GUIDE, lineHeight: LINE_GUIDE, colour: MUTED });
  flow.move(10);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Public API
// ─────────────────────────────────────────────────────────────────────────────

function statusLabel(status) {
  return ({
    draft: 'Draft', in_progress: 'In Progress', completed: 'Completed', archived: 'Archived',
  })[status] || status || '';
}

function formatDate(value) {
  if (!value) return '';
  const d = value instanceof Date ? value : new Date(value);
  if (isNaN(d.getTime())) return String(value);
  return d.toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' });
}

function formatDateTime(value) {
  if (!value) return '';
  const d = value instanceof Date ? value : new Date(value);
  if (isNaN(d.getTime())) return '';
  return d.toLocaleString('en-AU', {
    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', timeZone: 'UTC',
  });
}

/**
 * Render an interview document.
 *
 * @param {object}  opts
 * @param {object}  opts.template   a template or a stored template_schema snapshot
 * @param {string} [opts.mode]      'blank' | 'populated'   (default 'blank')
 * @param {object} [opts.record]    the interview record, for 'populated'
 * @returns {Promise<{ bytes: Buffer, pageCount: number, fieldCount: number }>}
 */
async function renderInterviewPdf({ template, mode = 'blank', record = null } = {}) {
  if (!template || !Array.isArray(template.sections)) {
    throw new Error('renderInterviewPdf: a template with sections is required');
  }

  const pdf = await PDFDocument.create();
  const fonts = {
    regular: await pdf.embedFont(StandardFonts.Helvetica),
    bold: await pdf.embedFont(StandardFonts.HelveticaBold),
    italic: await pdf.embedFont(StandardFonts.HelveticaOblique),
  };

  const populated = mode === 'populated' && record;
  const responses = populated ? { ...(record.responses || {}) } : {};
  if (populated) {
    // Ratings and recommendation live in their own columns; the renderer only
    // knows the question grammar, so they are merged back under their keys.
    const index = tpl.questionIndex(template);
    for (const [key, q] of index) {
      if (q.type === 'ratings' && record.ratings) responses[key] = record.ratings;
      if (q.type === 'choice' && q.emphasis && record.recommendation !== undefined && record.recommendation !== null) {
        responses[key] = { option: record.recommendation, detail: '' };
      }
    }
  }

  const header = populated ? {
    candidateName: record.candidate_name || '',
    position: record.position || '',
    interviewDate: formatDate(record.interview_date),
    interviewers: record.interviewers || '',
    status: statusLabel(record.status),
    createdByName: record.created_by_name || '',
    completedAtText: formatDateTime(record.completed_at),
    postCompletionEdits: Number(record.post_completion_edits) || 0,
    generatedAtText: formatDateTime(new Date()),
  } : {
    candidateName: '', position: '', interviewDate: '', interviewers: '',
  };

  const flow = new Flow(pdf, fonts, {
    footer: template.documentFooter || `OPAL THERAPY | ${(template.name || 'INTERVIEW').toUpperCase()}`,
  });

  renderTitleBlock(flow, template);
  if (populated) renderProvenance(flow, header);
  renderCandidatePanel(flow, header, mode);

  template.sections.forEach((section) => {
    renderSectionBar(flow, section);
    (section.questions || []).forEach((question) => {
      renderQuestion(flow, question, responses, mode);
      flow.move(4);
    });
    if (Array.isArray(section.signoff) && section.signoff.length) {
      renderSignoff(flow, section.signoff, responses, mode, header);
    }
    flow.move(8);
  });

  flow.finish();

  // Regenerate every appearance with the document's own font so a reader that
  // trusts the stored appearance shows the same text as one that rebuilds it.
  try { flow.form.updateFieldAppearances(fonts.regular); } catch (_) { /* appearances stay as built */ }

  const bytes = Buffer.from(await pdf.save({ updateFieldAppearances: false }));
  return { bytes, pageCount: flow.pages.length, fieldCount: flow.form.getFields().length };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Filenames
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build a download filename that is safe in a Content-Disposition header, on
 * every filesystem the practice uses, and readable by a person filing it.
 * Path separators, quotes, control characters and leading dots cannot survive.
 */
/**
 * Latin letters NFKD does not decompose.
 *
 * Normalising to NFKD splits e-acute into "e" plus a combining accent, which
 * the strip below then removes — but Ø, Æ, Ð, Þ, ß and Ł are single
 * indivisible letters, so NFKD leaves them whole and the strip deletes them
 * outright. Without this map, Renée Müller-Ødegård files as "Muller_degard".
 */
const FILENAME_FOLD = {
  'Ø': 'O', 'ø': 'o', 'Æ': 'AE', 'æ': 'ae', 'Œ': 'OE', 'œ': 'oe',
  'Đ': 'D', 'đ': 'd', 'Ð': 'D', 'ð': 'd', 'Þ': 'Th', 'þ': 'th',
  'ß': 'ss', 'Ł': 'L', 'ł': 'l', 'Ħ': 'H', 'ħ': 'h',
  'Ŧ': 'T', 'ŧ': 't', 'Ŋ': 'N', 'ŋ': 'n', 'İ': 'I', 'ı': 'i', 'ſ': 's',
};

function sanitiseFilenamePart(value, max = 60) {
  // Straight from the raw value, NOT via toWinAnsi: a filename wants the
  // letters transliteration would otherwise expand ('[yes]' for a tick).
  return String(value === null || value === undefined ? '' : value)
    .replace(/[ØøÆæŒœĐđÐðÞþßŁłĦħŦŧŊŋİıſ]/g, (c) => FILENAME_FOLD[c])
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, max) || 'Unnamed';
}

function blankFilename(template) {
  const stem = template.filenameStem
    || `Opal_Therapy_${sanitiseFilenamePart(template.name)}_Template`;
  return `${sanitiseFilenamePart(stem, 120)}.pdf`;
}

function recordFilename(template, record) {
  const who = sanitiseFilenamePart(record.candidate_name || 'Candidate', 50);
  const when = (() => {
    const d = record.interview_date ? new Date(record.interview_date) : new Date(record.created_at || Date.now());
    return isNaN(d.getTime()) ? 'undated' : d.toISOString().slice(0, 10);
  })();
  const stem = template.key === 'ot-interview'
    ? 'Opal_Therapy_OT_Interview'
    : `Opal_Therapy_${sanitiseFilenamePart(template.name, 60)}`;
  return `${stem}_${who}_${when}.pdf`;
}

module.exports = {
  renderInterviewPdf,
  blankFilename,
  recordFilename,
  sanitiseFilenamePart,
  toWinAnsi,
  wrapText,
  // Geometry, exported so the tests assert against the real numbers.
  PAGE_W,
  PAGE_H,
  CONTENT_W,
  MEASURE_INSET,
  SPARE_LINES,
  LINE_ANSWER,
};
