'use strict';

/**
 * Regenerate docs/ONBOARDING_POLICY_LIBRARY.md — the tracker for the 29
 * Opal-authored policies.
 *
 *   node backend/scripts/policy-tracker.js            # print to stdout
 *   node backend/scripts/policy-tracker.js --write    # write the docs file
 *
 * Read-only against the database. The point of generating it rather than
 * maintaining it by hand is that a hand-maintained checklist of 29 documents
 * tells you what somebody believed last time they edited it, which is exactly
 * the failure the ONBOARDING_DOCUMENT_CHECKLIST warned about for the library
 * itself.
 *
 * Runs without a database: the live columns simply read "—", so the tracker is
 * still generable from a checkout alone.
 */

const fs = require('fs');
const path = require('path');
const policies = require('../onboarding-policies');

const WRITE = process.argv.includes('--write');
const OUT = path.join(__dirname, '..', '..', 'docs', 'ONBOARDING_POLICY_LIBRARY.md');

/** Live state per code: what the library actually holds right now. */
async function liveState() {
  const state = new Map();
  let pool;
  try {
    ({ pool } = require('../database'));
    const { rows } = await pool.query(`
      SELECT d.code, d.status, d.content_status, d.current_version,
             (SELECT COUNT(*) FROM onboarding_document_versions v WHERE v.document_id = d.id) AS versions,
             (SELECT MAX(v.version) FROM onboarding_document_versions v
               WHERE v.document_id = d.id AND v.status = 'draft') AS latest_draft,
             (SELECT LENGTH(COALESCE(v.body, '')) FROM onboarding_document_versions v
               WHERE v.document_id = d.id AND v.status = 'published'
               ORDER BY v.version DESC LIMIT 1) AS published_bytes
        FROM onboarding_documents d
       WHERE d.classification = 'OPAL_POLICY' OR d.code LIKE 'DOC\\_%'`);
    for (const r of rows) state.set(r.code, r);
    await pool.end();
  } catch (err) {
    if (pool) { try { await pool.end(); } catch { /* already closed */ } }
    return { state, reachable: false, reason: err.message };
  }
  return { state, reachable: true };
}

/**
 * A published version short enough to be a stub is a stub.
 *
 * Both staging and dev seeded the library with a title and one line — 'Dev QA
 * content.', 'Synthetic staging content.' — and PUBLISHED it. So the library's
 * own status columns say `published/available` for documents that contain
 * nothing. Reporting that as done would make this tracker agree with the bug it
 * exists to surface, and no real policy here is under 500 words.
 */
const STUB_BYTES = 400;

function isStub(row) {
  const bytes = Number(row?.published_bytes || 0);
  return bytes > 0 && bytes < STUB_BYTES;
}

function published(row) {
  return row?.status === 'published' && row?.content_status === 'available' && !isStub(row);
}

/** What an Owner still has to do to this document, in one phrase. */
function nextStep(row, confirmations) {
  if (!row) return 'no library slot';
  if (isStub(row)) {
    return Number(row.latest_draft) > 0
      ? `**placeholder is live** — publish v${row.latest_draft} over it`
      : '**placeholder is live** — load and publish a real draft';
  }
  if (published(row)) return 'published — review at cycle';
  if (Number(row.latest_draft) > 0) return `review draft v${row.latest_draft}, resolve ${confirmations}`;
  if (Number(row.versions) > 0) return 'version exists, not a generated draft';
  return 'load the draft';
}

async function main() {
  const all = policies.loadAll();
  const { state, reachable, reason } = await liveState();
  // `state` is fetched with a broad predicate — DOC_% also matches the official
  // Fair Work and NDIS statements, which this directory does not own. Count
  // only the slots there is a policy file for, or the totals quietly describe
  // a different set of documents from the table above them.
  const mine = all.map((p) => state.get(p.code)).filter(Boolean);

  const stamp = new Date().toISOString().slice(0, 10);
  const totalConfirm = all.reduce((n, p) => n + p.confirmations.length, 0);
  const totalWords = all.reduce((n, p) => n + p.body.split(/\s+/).length, 0);

  const out = [];
  out.push('# Opal policy library — the 29 documents Opal must write');
  out.push('');
  out.push('Generated by `node backend/scripts/policy-tracker.js --write`. Do not hand-edit —');
  out.push('edit the policy files in `backend/onboarding-policies/` and regenerate.');
  out.push('');
  out.push(`Last generated: ${stamp}`);
  if (!reachable) out.push(`Live library state unavailable (${reason}). Columns show "—".`);
  out.push('');
  out.push('The other seven documents in the checklist are not here: five are statutory or');
  out.push('regulator documents Opal republishes verbatim, and two link to the regulator.');
  out.push('See [ONBOARDING_DOCUMENT_CHECKLIST.md](ONBOARDING_DOCUMENT_CHECKLIST.md).');
  out.push('');
  out.push('## Where each document stands');
  out.push('');
  out.push('`Ack` — the employee must acknowledge it. `?` — unresolved `[TO CONFIRM: …]` markers');
  out.push('in the drafted text: facts only the Owner can supply. `stub` — the library has a');
  out.push('PUBLISHED version holding seeded test text, which an employee can already see.');
  out.push('');
  out.push('| ☐ | Tier | Document | Area | Ack | Words | ? | Library | Next step |');
  out.push('|---|---|---|---|---|---|---|---|---|');

  for (const p of [...all].sort((a, b) => a.tier - b.tier || a.title.localeCompare(b.title))) {
    const row = state.get(p.code);
    const live = !row ? '—' : (isStub(row) ? `stub v${row.current_version}` : `${row.status}/${row.content_status}`);
    out.push(`| ☐ | ${p.tier} | ${p.title} | ${p.category} | ${p.acknowledgement ? 'yes' : '—'} `
      + `| ${p.body.split(/\s+/).length} | ${p.confirmations.length} | ${live} | ${nextStep(row, p.confirmations.length)} |`);
  }

  out.push('');
  out.push('## Totals');
  out.push('');
  out.push('| | |');
  out.push('|---|---|');
  out.push(`| Documents drafted | ${all.length} |`);
  out.push(`| Tier 1 · 2 · 3 | ${[1, 2, 3].map((t) => all.filter((p) => p.tier === t).length).join(' · ')} |`);
  out.push(`| Require acknowledgement | ${all.filter((p) => p.acknowledgement).length} |`);
  out.push(`| Words written | ${totalWords.toLocaleString('en-AU')} |`);
  out.push(`| Owner decisions outstanding | ${totalConfirm} |`);
  out.push(`| Live with real content | ${mine.filter(published).length} |`);
  out.push(`| Live with a placeholder an employee can see | ${mine.filter(isStub).length} |`);
  out.push(`| Drafted into the library, awaiting review | ${mine.filter((r) => Number(r.latest_draft) > 0).length} |`);
  out.push('');
  out.push('## What the Owner has to supply');
  out.push('');
  out.push('Every marker, grouped by document, so a decision made once can be applied everywhere');
  out.push('it appears rather than rediscovered per policy.');
  out.push('');

  for (const p of [...all].sort((a, b) => a.tier - b.tier || a.title.localeCompare(b.title))) {
    if (!p.confirmations.length) continue;
    out.push(`### ${p.title} · Tier ${p.tier} · \`${p.code}\``);
    out.push('');
    for (const c of p.confirmations) {
      out.push(`- ${c.replace(/^\[TO CONFIRM:\s*/, '').replace(/\]$/, '')}`);
    }
    out.push('');
  }

  out.push('## Working on these');
  out.push('');
  out.push('```bash');
  out.push('node backend/scripts/load-policy-drafts.js                # dry run');
  out.push('node backend/scripts/load-policy-drafts.js --apply        # create drafts');
  out.push('node backend/scripts/load-policy-drafts.js --apply --only POL_WHS');
  out.push('node backend/scripts/policy-tracker.js --write            # refresh this file');
  out.push('cd backend && npx jest tests/onboarding-policy-library.test.js');
  out.push('```');
  out.push('');
  out.push('Nothing in that list publishes anything. A draft becomes visible to an employee');
  out.push('only when an Owner opens it in the document library and publishes that version.');
  out.push('');

  const text = out.join('\n');
  if (WRITE) {
    fs.writeFileSync(OUT, text);
    console.log(`Wrote ${path.relative(process.cwd(), OUT)} — ${all.length} documents, ${totalConfirm} outstanding decisions.`);
  } else {
    console.log(text);
  }
}

main().catch((err) => { console.error(err); process.exitCode = 1; });
