'use strict';

/**
 * INTERVIEW PDF — the no-loss guarantee, proved rather than asserted.
 *
 * The whole point of this renderer is that an interview answer of any length
 * survives export. That is not a property you can eyeball; these tests read
 * the generated bytes back with pdf-lib and compare the recovered field values
 * to what went in, character for character.
 *
 * The load-bearing test is `wrapping can never overflow what pdf-lib lays
 * out`: it runs BOTH layout engines — this module's measurement and pdf-lib's
 * own layoutMultilineText, the code that actually draws the appearance — over
 * adversarial inputs and asserts pdf-lib never needs more lines than the box
 * was sized for. Everything else about "no clipping" follows from that.
 */

const { PDFDocument, StandardFonts } = require('pdf-lib');
const { layoutMultilineText } = require('pdf-lib/cjs/api/text/layout');

const tpl = require('../interview-templates');
const pdf = require('../interview-pdf');

const TEMPLATE = tpl.OT_INTERVIEW;

/** A believable long answer: fourteen real paragraphs, not one repeated word. */
function longAnswer(paragraphs = 14) {
  const sentence = 'The candidate described a community visit in considerable detail, including how '
    + 'they managed an unexpected escalation with a parent, the environmental assessment they '
    + 'completed, and the follow-up they arranged with the support coordinator.';
  return Array.from({ length: paragraphs }, (_, i) =>
    `Paragraph ${i + 1}. ${sentence} ${sentence} ${sentence}`).join('\n\n');
}

function baseRecord(overrides = {}) {
  return Object.assign({
    id: '11111111-1111-1111-1111-111111111111',
    candidate_name: 'Jane Smith',
    position: 'Occupational Therapist',
    interview_date: '2026-08-20',
    interviewers: 'Antony Xavier',
    status: 'completed',
    created_by_name: 'Antony Xavier',
    completed_at: '2026-08-20T04:00:00.000Z',
    created_at: '2026-08-19T04:00:00.000Z',
    post_completion_edits: 0,
    responses: {},
    ratings: {},
    recommendation: null,
  }, overrides);
}

/** Reload a generated document and return { doc, form, fields, textOf }. */
async function reload(bytes) {
  const doc = await PDFDocument.load(bytes);
  const form = doc.getForm();
  const fields = form.getFields();
  const names = fields.map((f) => f.getName());
  const textOf = (name) => {
    try { return form.getTextField(name).getText() || ''; } catch (_) { return null; }
  };
  /** Reassemble an answer that the renderer split across pages. */
  const wholeAnswer = (key) => names
    .filter((n) => n === key || n.startsWith(`${key}__cont`))
    .sort((a, b) => (a.length - b.length) || a.localeCompare(b))
    .map(textOf)
    .join('\n');
  return { doc, form, fields, names, textOf, wholeAnswer };
}

// ═══════════════════════════════════════════════════════════════════════════
//  The load-bearing invariant
// ═══════════════════════════════════════════════════════════════════════════

describe('wrapping can never overflow what pdf-lib lays out', () => {
  let font;
  beforeAll(async () => {
    const doc = await PDFDocument.create();
    font = await doc.embedFont(StandardFonts.Helvetica);
  });

  // pdf-lib's own geometry for a text field appearance:
  //   bounds.width = fieldWidth - (borderWidth + padding) * 2, padding = 1
  // The renderer uses borderWidth 0.7 on a full-content-width field.
  const PDFLIB_WIDTH = pdf.CONTENT_W - (0.7 + 1) * 2;
  const MEASURE_WIDTH = pdf.CONTENT_W - pdf.MEASURE_INSET;

  const SAMPLES = {
    'ordinary prose': longAnswer(3),
    'hard paragraph breaks': 'One.\n\nTwo is longer and will certainly wrap because it just '
      + 'keeps going and going and going and going and going and going.\n\nThree.',
    'a 400-character single token': `Prefix ${'A'.repeat(400)} suffix`,
    'a pasted URL': 'See https://example.invalid/'.concat('very-long-path-segment/'.repeat(20)),
    'accented Latin-1': 'Renée Müller-Ødegård discussed rôle clarity, naïve assumptions and '
      + 'café-based sessions in Åre and Ipswich. '.repeat(8),
    'many short tokens': 'a b c d e f g h i j k l m n o p q r s t u v w x y z '.repeat(20),
    'leading and trailing whitespace': '   \n\n   Answer after blank lines.   \n\n   ',
    'underscore rule': '_'.repeat(300),
    'one very long word, no spaces at all': 'Z'.repeat(2000),
    'CJK and emoji, transliterated': 'Candidate 日本語 name 🎉 with arrows → and ≥ signs. '.repeat(10),
    'empty': '',
    'single space': ' ',
    'newlines only': '\n\n\n\n',
  };

  for (const [name, text] of Object.entries(SAMPLES)) {
    test(`pdf-lib needs no more lines than the box was sized for: ${name}`, () => {
      const mine = pdf.wrapText(text, font, 9, MEASURE_WIDTH);

      // What the renderer will actually put in the field: the softened,
      // WinAnsi-safe source. Measure pdf-lib against exactly that.
      const source = pdf.wrapText(text, font, 9, MEASURE_WIDTH).join('\n');
      const theirs = layoutMultilineText(source, {
        alignment: 0, fontSize: 9, font,
        bounds: { x: 0, y: 0, width: PDFLIB_WIDTH, height: 1e6 },
      }).lines.length;

      // The box holds mine.length + SPARE_LINES lines. pdf-lib must fit in it.
      expect(theirs).toBeLessThanOrEqual(mine.length + pdf.SPARE_LINES);
    });
  }

  test('every measured line actually fits the column it was measured against', () => {
    for (const text of Object.values(SAMPLES)) {
      for (const line of pdf.wrapText(text, font, 9, MEASURE_WIDTH)) {
        expect(font.widthOfTextAtSize(line, 9)).toBeLessThanOrEqual(MEASURE_WIDTH + 0.001);
      }
    }
  });

  test('the box is always taller than the lines pdf-lib will draw into it', () => {
    // pdf-lib draws at heightAtSize(size) * 1.2 and clips at
    // fieldHeight - (borderWidth + 1) * 2.
    const pdflibLine = font.heightAtSize(9) * 1.2;
    expect(pdflibLine).toBeLessThanOrEqual(pdf.LINE_ANSWER);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  Blank template
// ═══════════════════════════════════════════════════════════════════════════

describe('blank fillable template', () => {
  let out;
  let loaded;
  beforeAll(async () => {
    out = await pdf.renderInterviewPdf({ template: TEMPLATE, mode: 'blank' });
    loaded = await reload(out.bytes);
  });

  test('generates a real PDF', () => {
    expect(Buffer.isBuffer(out.bytes)).toBe(true);
    expect(out.bytes.slice(0, 5).toString()).toBe('%PDF-');
    expect(out.pageCount).toBeGreaterThanOrEqual(5);
  });

  test('is fillable — proper AcroForm fields, not drawn rectangles', () => {
    expect(loaded.fields.length).toBeGreaterThan(40);
    const kinds = new Set(loaded.fields.map((f) => f.constructor.name));
    expect(kinds.has('PDFTextField')).toBe(true);
    expect(kinds.has('PDFCheckBox')).toBe(true);
    expect(kinds.has('PDFRadioGroup')).toBe(true);
  });

  test('narrative fields are multiline and, crucially, carry NO maximum length', () => {
    const text = loaded.fields.filter((f) => f.constructor.name === 'PDFTextField');
    const multiline = text.filter((f) => f.isMultiline());
    expect(multiline.length).toBeGreaterThan(25);
    // The source template capped every field at 100 characters. None here does.
    for (const f of text) expect(f.getMaxLength()).toBeUndefined();
  });

  test('every field name is unique — no shared field writing three boxes at once', () => {
    expect(new Set(loaded.names).size).toBe(loaded.names.length);
  });

  test('the candidate block and every question have a field of their own', () => {
    for (const key of ['candidate_name', 'interview_date', 'interviewers', 'role_position']) {
      expect(loaded.names).toContain(key);
    }
    tpl.eachQuestion(TEMPLATE, (q) => {
      if (q.type === 'checkboxes') {
        q.options.forEach((o) => expect(loaded.names).toContain(`${q.key}__${o.key}`));
      } else if (q.type === 'ratings') {
        q.rows.forEach((r) => expect(loaded.names).toContain(`${q.key}__${r.key}`));
      } else {
        expect(loaded.names).toContain(q.key);
      }
    });
  });

  test('single-choice questions are radio groups, so contradictory answers are impossible', () => {
    const recommendation = loaded.form.getRadioGroup('recommendation');
    expect(recommendation.getOptions().sort()).toEqual(['do_not_progress', 'hold', 'progress']);
    expect(recommendation.getSelected()).toBeUndefined();
    const clinical = loaded.form.getRadioGroup('ratings__clinical_reasoning');
    expect(clinical.getOptions()).toEqual(['1', '2', '3', '4', '5']);
  });

  test('nothing is pre-filled', () => {
    expect(loaded.textOf('candidate_name')).toBe('');
    expect(loaded.textOf('client_groups_notes')).toBe('');
    expect(loaded.form.getCheckBox('client_groups__adults').isChecked()).toBe(false);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  Populated interview
// ═══════════════════════════════════════════════════════════════════════════

describe('populated interview PDF', () => {
  const LONG = longAnswer(14);
  const MULTI_PARA = 'She described paediatric caseloads first.\n\n'
    + 'Then adult community work, including two NDIS plan reviews.\n\n'
    + 'Finally, a short placement in a rehabilitation ward.';

  let out;
  let loaded;

  beforeAll(async () => {
    out = await pdf.renderInterviewPdf({
      template: TEMPLATE,
      mode: 'populated',
      record: baseRecord({
        responses: {
          client_groups: ['paediatrics', 'disability', 'neurological'],
          client_groups_notes: MULTI_PARA,
          independent_visits: LONG,
          mixed_caseload: 'Comfortable — has done it before.',
          availability: { option: 'other', detail: '0.8 FTE, school hours' },
          expected_salary: '$95,000 + super',
          overall_observations: 'Strong candidate throughout. '.repeat(30),
          key_strengths: 'Reflective; safe; warm.',
          next_steps: 'Offer subject to references — NDIS worker screening required.',
          signoff_interviewer: 'A. Xavier',
        },
        ratings: {
          clinical_reasoning: 4, communication: 5, self_awareness: 3,
          community_readiness: 4, culture_fit: 5,
        },
        recommendation: 'progress',
      }),
    });
    loaded = await reload(out.bytes);
  });

  test('the candidate\'s details are on the document', () => {
    expect(loaded.textOf('candidate_name')).toBe('Jane Smith');
    expect(loaded.textOf('role_position')).toBe('Occupational Therapist');
    expect(loaded.textOf('interviewers')).toBe('Antony Xavier');
    expect(loaded.textOf('interview_date')).toBe('20 Aug 2026');
  });

  test('a multi-paragraph answer keeps its paragraphs', () => {
    expect(loaded.textOf('client_groups_notes')).toBe(MULTI_PARA);
  });

  test('THE LONG ANSWER IS NOT DROPPED — every character survives the export', () => {
    const recovered = loaded.wholeAnswer('independent_visits');
    const expected = pdf.toWinAnsi(LONG);
    // Line breaks move (the answer is split across pages by design); no
    // character of it may be missing.
    const strip = (s) => s.replace(/\s+/g, ' ').trim();
    expect(strip(recovered)).toBe(strip(expected));
    expect(strip(recovered).length).toBeGreaterThan(9000);
  });

  test('the long answer actually split across pages, and each part is its own field', () => {
    const parts = loaded.names.filter(
      (n) => n === 'independent_visits' || n.startsWith('independent_visits__cont'));
    expect(parts.length).toBeGreaterThan(1);
    parts.forEach((n) => expect(typeof loaded.textOf(n)).toBe('string'));
  });

  test('the document grew extra pages rather than clipping', async () => {
    const blank = await pdf.renderInterviewPdf({ template: TEMPLATE, mode: 'blank' });
    expect(out.pageCount).toBeGreaterThan(blank.pageCount);
  });

  test('ticked boxes are ticked, unticked ones are not', () => {
    expect(loaded.form.getCheckBox('client_groups__paediatrics').isChecked()).toBe(true);
    expect(loaded.form.getCheckBox('client_groups__disability').isChecked()).toBe(true);
    expect(loaded.form.getCheckBox('client_groups__neurological').isChecked()).toBe(true);
    expect(loaded.form.getCheckBox('client_groups__adults').isChecked()).toBe(false);
    expect(loaded.form.getCheckBox('client_groups__mental_health').isChecked()).toBe(false);
  });

  test('every rating is on the document, against its own category', () => {
    expect(loaded.form.getRadioGroup('ratings__clinical_reasoning').getSelected()).toBe('4');
    expect(loaded.form.getRadioGroup('ratings__communication').getSelected()).toBe('5');
    expect(loaded.form.getRadioGroup('ratings__self_awareness').getSelected()).toBe('3');
    expect(loaded.form.getRadioGroup('ratings__community_readiness').getSelected()).toBe('4');
    expect(loaded.form.getRadioGroup('ratings__culture_fit').getSelected()).toBe('5');
  });

  test('the recommendation is on the document, and only one of them', () => {
    expect(loaded.form.getRadioGroup('recommendation').getSelected()).toBe('progress');
  });

  test('a choice with a detail carries both', () => {
    expect(loaded.form.getRadioGroup('availability').getSelected()).toBe('other');
    expect(loaded.textOf('availability__detail')).toBe('0.8 FTE, school hours');
  });

  test('an unanswered question is an empty box, not a missing one', () => {
    expect(loaded.names).toContain('good_supervision');
    expect(loaded.textOf('good_supervision')).toBe('');
  });

  test('the document stays editable — every field is still a real form field', () => {
    const text = loaded.fields.filter((f) => f.constructor.name === 'PDFTextField');
    expect(text.length).toBeGreaterThan(25);
    for (const f of text) {
      expect(f.isReadOnly()).toBe(false);
      expect(f.getMaxLength()).toBeUndefined();
    }
  });

  test('an explicit sign-off wins; an absent one falls back to the record', async () => {
    expect(loaded.textOf('signoff_interviewer')).toBe('A. Xavier');
    const fallback = await pdf.renderInterviewPdf({
      template: TEMPLATE, mode: 'populated', record: baseRecord(),
    });
    const back = await reload(fallback.bytes);
    expect(back.textOf('signoff_interviewer')).toBe('Antony Xavier');
    expect(back.textOf('signoff_date')).toBe('20 Aug 2026');
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  Hostile and awkward input
// ═══════════════════════════════════════════════════════════════════════════

describe('special characters never break generation', () => {
  const NASTY = {
    'CJK, emoji and symbols': 'Nguyễn 日本語 Ω ✓ 🎉 → ≥ ± « » — – … •',
    'RTL and combining marks': 'مرحبا שלום éè ä',
    'control characters': 'before [31mafter',
    'HTML and script': '<script>alert("xss")</script> & <img src=x onerror=alert(1)>',
    'PDF syntax': ') Tj 0 0 0 rg BT /F1 99 Tf ( endstream endobj 1 0 obj <<>>',
    'SQL-ish': "'; DROP TABLE interview_records; --",
    'nul-ish and BOM': '﻿leading BOM​zero width nbsp',
    'unbalanced quotes and backslashes': '\\\\ " \' \\n \\t (( ))',
    'very long line, no spaces': 'µ'.repeat(3000),
    'every Latin-1 character': Array.from({ length: 96 }, (_, i) => String.fromCharCode(160 + i)).join(''),
  };

  for (const [name, value] of Object.entries(NASTY)) {
    test(`generates cleanly: ${name}`, async () => {
      const out = await pdf.renderInterviewPdf({
        template: TEMPLATE,
        mode: 'populated',
        record: baseRecord({
          candidate_name: value,
          position: value,
          interviewers: value,
          responses: { client_groups_notes: value, overall_observations: value },
        }),
      });
      expect(out.bytes.slice(0, 5).toString()).toBe('%PDF-');
      expect(out.pageCount).toBeGreaterThan(0);
      const loaded = await reload(out.bytes);
      // Whatever it became, it is a string in a real field — never a crash and
      // never a silently absent field.
      expect(typeof loaded.textOf('client_groups_notes')).toBe('string');
    });
  }

  test('transliteration keeps Latin-1 and CP1252 exactly, and folds Extended-A', () => {
    // CP1252 covers all of Latin-1 plus a handful of extras (S-caron among
    // them), so these pass through untouched rather than being folded.
    expect(pdf.toWinAnsi('Renée Müller-Ødegård çà')).toBe('Renée Müller-Ødegård çà');
    expect(pdf.toWinAnsi('Šarka')).toBe('Šarka');
    // Latin Extended-A has no CP1252 form, so it folds to its base letter.
    expect(pdf.toWinAnsi('Łukasz Ngātai Đặng')).toBe('Lukasz Ngatai D?ng');
  });

  test('an unrepresentable script leaves a visible placeholder, never a crash', () => {
    expect(pdf.toWinAnsi('日本語')).toBe('???');
    expect(pdf.toWinAnsi('→ becomes')).toBe('-> becomes');
  });

  test('control characters are dropped and line endings normalised', () => {
    expect(pdf.toWinAnsi('a bc')).toBe('abc');
    expect(pdf.toWinAnsi('a\r\nb\rc\nd')).toBe('a\nb\nc\nd');
    expect(pdf.toWinAnsi('a\tb')).toBe('a    b');
  });
});

describe('an empty and a maximal interview both render', () => {
  test('a brand-new record with no answers at all', async () => {
    const out = await pdf.renderInterviewPdf({
      template: TEMPLATE, mode: 'populated',
      record: baseRecord({ status: 'draft', candidate_name: 'A', completed_at: null }),
    });
    expect(out.pageCount).toBeGreaterThanOrEqual(5);
  });

  test('every question answered at length — many pages, nothing lost', async () => {
    const responses = {};
    tpl.eachQuestion(TEMPLATE, (q) => {
      if (q.type === 'longtext') responses[q.key] = longAnswer(4);
    });
    const out = await pdf.renderInterviewPdf({
      template: TEMPLATE, mode: 'populated', record: baseRecord({ responses }),
    });
    // Every narrative question answered at four paragraphs each: three times
    // the blank template's length, and every word still present.
    expect(out.pageCount).toBeGreaterThan(15);

    const loaded = await reload(out.bytes);
    const strip = (s) => s.replace(/\s+/g, ' ').trim();
    const expected = strip(pdf.toWinAnsi(longAnswer(4)));
    // Spot-check the first, a middle and the last narrative question.
    for (const key of ['client_groups_notes', 'rapport', 'next_steps']) {
      expect(strip(loaded.wholeAnswer(key))).toBe(expected);
    }
  }, 30000);

  test('a template snapshot from an older version still renders', async () => {
    // Exactly what a stored record holds: a frozen copy that may no longer
    // match the live module.
    const snapshot = tpl.snapshotOf(TEMPLATE);
    snapshot.version = 1;
    snapshot.sections = snapshot.sections.slice(0, 3);
    snapshot.sections[0].title = 'Experience (as asked in 2026)';
    const out = await pdf.renderInterviewPdf({
      template: snapshot, mode: 'populated',
      record: baseRecord({ responses: { client_groups_notes: 'Historic answer.' } }),
    });
    const loaded = await reload(out.bytes);
    expect(loaded.textOf('client_groups_notes')).toBe('Historic answer.');
    // A question the live template has but this snapshot does not is absent —
    // the record was never asked it.
    expect(loaded.names).not.toContain('key_strengths');
  });

  test('a template with no sections is refused rather than producing a blank document', async () => {
    await expect(pdf.renderInterviewPdf({ template: { name: 'x' } })).rejects.toThrow(/sections/);
    await expect(pdf.renderInterviewPdf({})).rejects.toThrow(/sections/);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  Filenames
// ═══════════════════════════════════════════════════════════════════════════

describe('filenames', () => {
  test('the blank template has the name the practice files it under', () => {
    expect(pdf.blankFilename(TEMPLATE))
      .toBe('Opal_Therapy_Occupational_Therapist_Interview_Template.pdf');
  });

  test('a record names its candidate and its date', () => {
    expect(pdf.recordFilename(TEMPLATE, {
      candidate_name: 'Jane Smith', interview_date: '2026-08-20',
    })).toBe('Opal_Therapy_OT_Interview_Jane_Smith_2026-08-20.pdf');
  });

  test('accents survive as their base letters', () => {
    expect(pdf.recordFilename(TEMPLATE, {
      candidate_name: 'Renée Müller-Ødegård', interview_date: '2026-01-02',
    })).toBe('Opal_Therapy_OT_Interview_Renee_Muller_Odegard_2026-01-02.pdf');
  });

  const HOSTILE = [
    '../../../etc/passwd',
    'a/b\\c',
    'name"; attachment; filename="payroll',
    'CON',
    '..',
    'x'.repeat(300),
    ' nul',
    '<script>alert(1)</script>',
    '\n\rHeader-Injection: yes',
  ];

  for (const name of HOSTILE) {
    test(`a hostile candidate name cannot escape the filename: ${JSON.stringify(name.slice(0, 28))}`, () => {
      const out = pdf.recordFilename(TEMPLATE, { candidate_name: name, interview_date: '2026-08-20' });
      expect(out).toMatch(/^[A-Za-z0-9._-]+\.pdf$/);
      expect(out).not.toMatch(/[/\\"'\s;:]/);
      expect(out.length).toBeLessThan(140);
    });
  }

  test('an empty candidate name still produces a usable filename', () => {
    expect(pdf.recordFilename(TEMPLATE, { candidate_name: '', interview_date: '2026-08-20' }))
      .toBe('Opal_Therapy_OT_Interview_Candidate_2026-08-20.pdf');
  });

  test('an undated record is labelled undated rather than crashing', () => {
    const out = pdf.recordFilename(TEMPLATE, { candidate_name: 'X', interview_date: 'not a date' });
    expect(out).toMatch(/undated\.pdf$/);
  });
});
