'use strict';

/**
 * Quality-gate tests.
 *
 * Real bytes throughout — the documents are generated by the same builder the
 * seeder uses, so the test exercises the gate against the files it will
 * actually be asked to judge rather than against a fixture that cannot fail.
 */

const quality = require('../resource-file-quality');
const builder = require('../opal-document-builder');

const SPEC = {
  title: 'Test worksheet',
  subtitle: 'For the quality gate.',
  sections: [
    { heading: 'A section', guidance: 'Guidance line.', paragraphs: ['A paragraph of body text.'],
      fields: [{ label: 'A writing area', lines: 2 }],
      table: { headers: ['Left', 'Right'], rows: [['one', 'two']] } },
  ],
  limitations: ['Not clinically reviewed.'],
  footer: 'Draft.',
};

describe('format sniffing', () => {
  test('identifies by leading bytes, not by name', () => {
    expect(quality.sniffMagic(Buffer.from('%PDF-1.7\n'))).toBe('pdf');
    expect(quality.sniffMagic(Buffer.from([0x50, 0x4b, 0x03, 0x04]))).toBe('zip');
    expect(quality.sniffMagic(Buffer.from([0xd0, 0xcf, 0x11, 0xe0]))).toBe('ole');
    expect(quality.sniffMagic(Buffer.from('just text'))).toBe('unknown');
  });

  test('a Word document renamed .pdf fails the gate', async () => {
    const docx = await builder.buildDocx(SPEC);
    const verdict = await quality.assessFile(docx, { declaredFormat: 'pdf', declaredName: 'thing.pdf' });
    expect(verdict.passed).toBe(false);
    expect(verdict.failures.join(' ')).toMatch(/Declared PDF but the file begins with a zip/);
  });

  test('a legacy .doc presented as .docx is rejected as an OLE container', async () => {
    const ole = Buffer.concat([Buffer.from([0xd0, 0xcf, 0x11, 0xe0]), Buffer.alloc(600)]);
    const verdict = await quality.assessFile(ole, { declaredFormat: 'docx', declaredName: 'legacy.docx' });
    expect(verdict.passed).toBe(false);
    expect(verdict.failures.join(' ')).toMatch(/OLE compound file/);
  });

  test('an extension that disagrees with the declared format fails', async () => {
    const pdf = await builder.buildPdf(SPEC);
    const verdict = await quality.assessFile(pdf, { declaredFormat: 'pdf', declaredName: 'thing.docx' });
    expect(verdict.passed).toBe(false);
    expect(verdict.failures.join(' ')).toMatch(/extension \.docx does not match/);
  });

  test('an empty file fails', async () => {
    const verdict = await quality.assessFile(Buffer.alloc(0), { declaredFormat: 'pdf' });
    expect(verdict.passed).toBe(false);
    expect(verdict.failures.join(' ')).toMatch(/empty/);
  });

  test('corrupt PDF bytes fail rather than pass silently', async () => {
    const broken = Buffer.concat([Buffer.from('%PDF-1.7\n'), Buffer.from('not a pdf body')]);
    const verdict = await quality.assessFile(broken, { declaredFormat: 'pdf', declaredName: 'x.pdf' });
    expect(verdict.passed).toBe(false);
  });
});

describe('generated documents pass the gate', () => {
  test('PDF: parses, has a text layer, reports pages, no identifiers', async () => {
    const pdf = await builder.buildPdf(SPEC);
    const verdict = await quality.assessFile(pdf, { declaredFormat: 'pdf', declaredName: 'x.pdf' });
    expect(verdict.passed).toBe(true);
    expect(verdict.report.pageCount).toBeGreaterThan(0);
    expect(verdict.report.pdf.hasTextLayer).toBe(true);
    expect(verdict.report.pdf.blankPages).toHaveLength(0);
    expect(verdict.report.identifierFindings).toHaveLength(0);
    // Every page was parsed, not just counted.
    expect(verdict.report.pdf.perPage.every((p) => p.rendered)).toBe(true);
  });

  test('PDF accessibility is reported honestly as untagged', async () => {
    const pdf = await builder.buildPdf(SPEC);
    const verdict = await quality.assessFile(pdf, { declaredFormat: 'pdf', declaredName: 'x.pdf' });
    expect(verdict.report.accessibility).toBe('text-layer-present-tagging-unverified');
    expect(verdict.report.visualReviewRequired).toBe(true);
  });

  test('DOCX: valid package with a document part and text', async () => {
    const docx = await builder.buildDocx(SPEC);
    const verdict = await quality.assessFile(docx, { declaredFormat: 'docx', declaredName: 'x.docx' });
    expect(verdict.passed).toBe(true);
    expect(verdict.report.docx.hasDocumentXml).toBe(true);
    expect(verdict.report.docx.textChars).toBeGreaterThan(0);
  });

  test('DOCX carries alt text on the logo and marked table headers', async () => {
    const JSZip = require('jszip');
    const docx = await builder.buildDocx(SPEC);
    const zip = await JSZip.loadAsync(docx);
    const xml = await zip.file('word/document.xml').async('string');
    expect(xml).toContain('w:tblHeader');                       // header row marked
    expect(xml).toMatch(/descr="Opal Therapy logo"/);           // image alt text
    expect(xml).toContain('w:pStyle w:val="Heading1"');         // real heading styles
    const core = await zip.file('docProps/core.xml').async('string');
    expect(core).toContain('en-AU');
  });

  test('table content is wrapped, never truncated', async () => {
    const long = 'A deliberately long cell value that must not be cut off part way through a word';
    const spec = { ...SPEC, sections: [{ heading: 'T', table: { headers: ['H'], rows: [[long]] } }] };
    const pdf = await builder.buildPdf(spec);
    const inspected = await quality.inspectPdf(pdf);
    expect(inspected.hasTextLayer).toBe(true);
    // The final word must survive; truncation would drop it.
    const pdfjs = await quality.loadPdfjs();
    const doc = await pdfjs.getDocument({
      data: new Uint8Array(pdf), useWorkerFetch: false, isEvalSupported: false, useSystemFonts: false,
    }).promise;
    const page = await doc.getPage(1);
    const text = (await page.getTextContent()).items.map((i) => i.str).join(' ').replace(/\s+/g, ' ');
    await doc.destroy();
    expect(text).toContain('word');
  });
});

describe('client identifier scan', () => {
  test.each([
    ['email', 'contact jane.doe@example.com for details'],
    ['medicare-number', 'card 2123 45678 1 issued'],
    ['ndis-participant-number', 'participant 430123456 attends'],
    ['date-of-birth', 'born 14/03/1988 in Perth'],
    ['australian-phone', 'call 0412 345 678 today'],
  ])('detects %s', (kind, text) => {
    const findings = quality.scanForIdentifiers(text);
    expect(findings.map((f) => f.kind)).toContain(kind);
  });

  test('reports counts only — never the matched value', () => {
    const findings = quality.scanForIdentifiers('jane.doe@example.com and john@x.org');
    expect(findings[0].count).toBe(2);
    expect(JSON.stringify(findings)).not.toMatch(/jane|john|example/i);
  });

  test('a document containing an identifier fails the gate', async () => {
    const spec = {
      ...SPEC,
      sections: [{ heading: 'Contact', paragraphs: ['Reach the client on 0412 345 678.'] }],
    };
    const pdf = await builder.buildPdf(spec);
    const verdict = await quality.assessFile(pdf, { declaredFormat: 'pdf', declaredName: 'x.pdf' });
    expect(verdict.passed).toBe(false);
    expect(verdict.failures.join(' ')).toMatch(/Possible client identifiers/);
  });

  test('clean template text produces no findings', () => {
    expect(quality.scanForIdentifiers('Participant name and NDIS number')).toHaveLength(0);
  });
});
