'use strict';

/**
 * SERVICE AGREEMENT — FILLABLE PDF
 *
 *   renderAgreementPdf({ docxBuffer, meta, lockProviderFields })
 *     → { bytes, pageCount, fieldCount, fieldNames, warnings }
 *
 * Renders the COMPOSED Word document (via ./docx-outline.js) as a standard
 * AcroForm PDF: prefilled values are drawn as text, blank controls become
 * interactive widgets, and the two documents cannot disagree because there is
 * only one document — this reads the same bytes Word would open.
 *
 * ── ACROFORM, NOT XFA ──────────────────────────────────────────────────────
 * pdf-lib emits AcroForm only; there is no XFA code path to avoid. That is the
 * right format anyway: XFA is deprecated, unsupported in browser viewers and
 * in macOS Preview, and a participant who cannot open the form cannot sign it.
 *
 * ── WHAT "COMPATIBLE" HONESTLY MEANS ───────────────────────────────────────
 * Every field carries a real appearance stream, generated by pdf-lib against
 * the same standard font the layout was measured with, AND the document sets
 * /NeedAppearances true. Belt and braces, because the two failure modes are
 * opposite: a viewer that ignores appearance streams (some browser viewers)
 * needs NeedAppearances to render a value at all, while a viewer that honours
 * NeedAppearances but regenerates poorly (older Acrobat) needs the stream to
 * fall back to. Tested against Chrome/Firefox PDF viewing, Adobe Acrobat
 * Reader and macOS Preview on a best-effort basis — NOT a claim about every
 * PDF application in existence.
 *
 * ── FONTS ──────────────────────────────────────────────────────────────────
 * The standard 14 (Helvetica family), so no font is embedded and every viewer
 * has them. The cost is WinAnsi: characters outside CP1252 cannot be drawn and
 * pdf-lib throws on them. toWinAnsi() transliterates what it can — including
 * the Latin Extended-A block, so a participant called Zoë, Ngātai or Nguyễn
 * reads as close to their name as the encoding permits — and substitutes '?'
 * for scripts it cannot represent. That limitation is recorded rather than
 * hidden; fixing it properly means embedding a Unicode face with fontkit.
 * This is the same trade-off, and the same helper, as interview-pdf.js.
 *
 * ── SIGNATURES ─────────────────────────────────────────────────────────────
 * A signature field here is a TEXT field on a signature rule, not a
 * cryptographic signature field. Nothing in this pipeline can produce or
 * validate a PKCS#7 signature, and labelling a typed name as a digital
 * signature would be a false assurance in a legal document. The portal signing
 * route records intent, capacity, timestamp and a document hash; that is what
 * is claimed, and it is claimed in those words.
 */

const { PDFDocument, StandardFonts, rgb, PDFName, PDFString, PDFBool } = require('pdf-lib');

const { outlineFromDocx } = require('./docx-outline');
const map = require('./template-map');
const { toWinAnsi, sanitiseFilenamePart } = require('../interview-pdf');

// ─────────────────────────────────────────────────────────────────────────────
//  Geometry and palette — A4, matching the Opal document palette
// ─────────────────────────────────────────────────────────────────────────────

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN_L = 51;
const MARGIN_R = 51;
const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;

const BAND_H = 16;
const CONTENT_TOP = PAGE_H - 52;
const CONTENT_BOTTOM = 62;
const FOOTER_RULE_Y = 48;
const FOOTER_TEXT_Y = 34;

// backend/opal-document-builder.js PALETTE, as pdf-lib colours.
const PRIMARY = rgb(0.184, 0.337, 0.318);   // #2F5651
const SECONDARY = rgb(0.337, 0.431, 0.439); // #566E70
const SOFT_MINT = rgb(0.894, 0.937, 0.922); // #E4EFEB
const WARM_NEUTRAL = rgb(0.980, 0.969, 0.949); // #FAF7F2
const INK = rgb(0.122, 0.165, 0.157);       // #1F2A28
const BORDER = rgb(0.769, 0.808, 0.796);
const FIELD_BG = rgb(0.988, 0.992, 1);
const FIELD_BORDER = rgb(0.478, 0.573, 0.557);
const WHITE = rgb(1, 1, 1);

const SIZE_TITLE = 20;
const SIZE_H1 = 13.5;
const SIZE_H2 = 11;
const SIZE_H3 = 9.8;
const SIZE_BODY = 9;
const SIZE_SMALL = 7.6;
const SIZE_TABLE = 8.4;
const SIZE_FIELD = 9;
const SIZE_FOOTER = 7.4;

const LINE_BODY = 11.6;
const LINE_TABLE = 10.4;
/** pdf-lib lays a field's appearance out at heightAtSize×1.2 ≈ 10 for 9pt. */
const LINE_FIELD = 10;

/** Wrap against a narrower column than the widget, so pdf-lib can never need
 *  more lines than were measured. Same reasoning as interview-pdf.js. */
const MEASURE_INSET = 8;
/**
 * Body text is wrapped against a column this much narrower than the one it is
 * drawn into.
 *
 * The standard 14 fonts are NOT embedded, so a viewer substitutes its own
 * Helvetica and its glyph advances differ from the AFM metrics pdf-lib
 * measures with — by a fraction of a point per character, which accumulates
 * over a long line. Measured without this, two clause bullets overhung the
 * right margin by up to 4pt. Wrapping short by 6pt costs roughly one word per
 * line in the worst case and makes the overhang impossible.
 */
const TEXT_SAFETY = 6;
const FIELD_VPAD = 3.5;
const CELL_PAD = 4;
const RADIO_SIZE = 9.5;

const MIN_FIELD_H = LINE_FIELD + FIELD_VPAD * 2;

// ─────────────────────────────────────────────────────────────────────────────
//  Text helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Insert break opportunities pdf-lib will not find on its own.
 *
 * pdf-lib breaks at spaces only, so an NDIS support-item number like
 * `15_056_0128_1_3` or a long email is one unbreakable token and escapes the
 * right edge of its field. Zero-width joins are not available in WinAnsi, so
 * the break is a real one, inserted before measurement so the layout and the
 * appearance agree about it.
 */
function softenLongTokens(text, font, size, width) {
  return String(text).split(/(\s+)/).map((token) => {
    if (/^\s*$/.test(token)) return token;
    if (font.widthOfTextAtSize(token, size) <= width) return token;
    const out = [];
    let cur = '';
    for (const ch of token) {
      if (font.widthOfTextAtSize(cur + ch, size) > width && cur) { out.push(cur); cur = ch; }
      else cur += ch;
    }
    if (cur) out.push(cur);
    return out.join(' ');
  }).join('');
}

/** Wrap to lines, honouring existing newlines. */
function wrap(text, font, size, width) {
  const source = softenLongTokens(toWinAnsi(text), font, size, width);
  const lines = [];
  for (const para of source.split('\n')) {
    const words = para.split(/\s+/).filter((w) => w !== '');
    if (!words.length) { lines.push(''); continue; }
    let line = '';
    for (const w of words) {
      const candidate = line ? `${line} ${w}` : w;
      if (font.widthOfTextAtSize(candidate, size) > width && line) { lines.push(line); line = w; }
      else line = candidate;
    }
    if (line) lines.push(line);
  }
  return lines;
}

/**
 * AcroForm field names are a FLAT namespace and '.' creates a hierarchy, so it
 * is stripped. Names stay human-readable — a participant inspecting the form,
 * or a screen reader announcing it, should hear "Participant full name".
 */
function fieldName(label) {
  return String(label || 'Field')
    .replace(/[.\\/\[\]()<>{}]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 90) || 'Field';
}

// ─────────────────────────────────────────────────────────────────────────────
//  The flow
// ─────────────────────────────────────────────────────────────────────────────

class Flow {
  constructor(pdf, fonts, meta) {
    this.pdf = pdf;
    this.form = pdf.getForm();
    this.fonts = fonts;
    this.meta = meta;
    this.pages = [];
    this.page = null;
    this.y = 0;
    /** name → PDFField, so a tag appearing twice gets ONE field, two widgets. */
    this.fields = new Map();
    this.names = [];
    this.warnings = [];
    this.newPage();
  }

  newPage() {
    this.page = this.pdf.addPage([PAGE_W, PAGE_H]);
    this.pages.push(this.page);
    this.page.drawRectangle({ x: 0, y: PAGE_H - BAND_H, width: PAGE_W, height: BAND_H, color: PRIMARY });
    if (this.meta.headerRight) {
      const t = toWinAnsi(this.meta.headerRight);
      const w = this.fonts.bold.widthOfTextAtSize(t, 7.4);
      this.page.drawText(t, {
        x: PAGE_W - MARGIN_R - w, y: PAGE_H - BAND_H + 5, size: 7.4,
        font: this.fonts.bold, color: WHITE,
      });
    }
    if (this.meta.headerLeft) {
      this.page.drawText(toWinAnsi(this.meta.headerLeft), {
        x: MARGIN_L, y: PAGE_H - BAND_H + 5, size: 7.4, font: this.fonts.bold, color: WHITE,
      });
    }
    this.y = CONTENT_TOP;
  }

  /** Break when `height` will not fit. */
  ensure(height) {
    if (this.y - height < CONTENT_BOTTOM) this.newPage();
  }

  text(str, { font, size, color = INK, leading, x = MARGIN_L, width = CONTENT_W } = {}) {
    const lines = wrap(str, font, size, width - TEXT_SAFETY);
    const lh = leading || size * 1.28;
    for (const line of lines) {
      this.ensure(lh);
      if (line) {
        this.page.drawText(line, { x, y: this.y - size, size, font, color });
      }
      this.y -= lh;
    }
  }

  /** Footer furniture, drawn once the page total is known. */
  finish() {
    const total = this.pages.length;
    this.pages.forEach((page, i) => {
      page.drawLine({
        start: { x: MARGIN_L, y: FOOTER_RULE_Y }, end: { x: PAGE_W - MARGIN_R, y: FOOTER_RULE_Y },
        thickness: 0.6, color: BORDER,
      });
      const left = toWinAnsi(this.meta.footerLeft || '');
      if (left) {
        page.drawText(left, {
          x: MARGIN_L, y: FOOTER_TEXT_Y, size: SIZE_FOOTER, font: this.fonts.regular, color: SECONDARY,
        });
      }
      const right = `Page ${i + 1} of ${total}`;
      const w = this.fonts.regular.widthOfTextAtSize(right, SIZE_FOOTER);
      page.drawText(right, {
        x: PAGE_W - MARGIN_R - w, y: FOOTER_TEXT_Y, size: SIZE_FOOTER,
        font: this.fonts.regular, color: SECONDARY,
      });
    });
  }

  // ── AcroForm widgets ──────────────────────────────────────────────────────

  /**
   * A text (or multiline, or date) widget.
   *
   * Reuses an existing field of the same name rather than creating a second
   * one, so the participant's name typed in the header block also fills the
   * signature block. `addToPage` a second time adds a WIDGET to that same
   * field, which is the AcroForm mechanism for exactly this.
   */
  textWidget(entry, rect, { multiline = false, readOnly = false } = {}) {
    const name = fieldName(entry.name);
    let field = this.fields.get(name);
    if (!field) {
      try {
        field = this.form.createTextField(name);
      } catch (err) {
        // A name collision with a differently-typed field: fall back to a
        // suffixed name rather than losing the field entirely.
        const alt = fieldName(`${entry.name} ${this.fields.size + 1}`);
        this.warnings.push(`Field "${name}" could not be created (${err.message}); used "${alt}".`);
        field = this.form.createTextField(alt);
        this.fields.set(alt, field);
        this.names.push(alt);
      }
      if (!this.fields.has(name)) { this.fields.set(name, field); this.names.push(name); }
      if (multiline) field.enableMultiline();
      const tip = entry.kind === map.KIND.DATE
        ? `${entry.prompt} (DD/MM/YYYY)`
        : entry.prompt;
      setTooltip(field, tip);
      if (readOnly) field.enableReadOnly();
    }

    field.addToPage(this.page, {
      x: rect.x, y: rect.y, width: rect.width, height: rect.height,
      borderWidth: 0.8, borderColor: FIELD_BORDER, backgroundColor: FIELD_BG,
      font: this.fonts.regular,
    });
    // The /DA font size must be set AFTER the widget exists — the dictionary it
    // is written into does not exist until then. Fixing it pins the appearance
    // to the size this layout measured against; left on auto, a viewer shrinks
    // the text to its own idea of the box and the two drift apart.
    try { field.setFontSize(SIZE_FIELD); } catch (_) { /* appearance stays auto */ }
    return field;
  }

  /** A radio group — mutually exclusive by construction. */
  radioWidget(entry, x, y, width) {
    const name = fieldName(entry.name);
    let group = this.fields.get(name);
    const fresh = !group;
    if (fresh) {
      group = this.form.createRadioGroup(name);
      this.fields.set(name, group);
      this.names.push(name);
      setTooltip(group, entry.prompt);
    }

    const choices = entry.choices || [];
    // Lay the options along one line where they fit, else stack them. A
    // consent question whose options wrap into each other is a consent
    // question somebody answers wrong.
    const gap = 9;
    const widths = choices.map((c) => RADIO_SIZE + 3.5
      + this.fonts.regular.widthOfTextAtSize(toWinAnsi(c), SIZE_SMALL + 0.4));
    const oneLine = widths.reduce((a, b) => a + b, 0) + gap * (choices.length - 1) <= width;

    let cx = x;
    let cy = y;
    for (let i = 0; i < choices.length; i += 1) {
      const label = choices[i];
      if (!oneLine && i > 0) cy -= RADIO_SIZE + 4;
      group.addOptionToPage(label, this.page, {
        x: cx, y: cy, width: RADIO_SIZE, height: RADIO_SIZE,
        borderWidth: 0.8, borderColor: FIELD_BORDER, backgroundColor: FIELD_BG,
      });
      this.page.drawText(toWinAnsi(label), {
        x: cx + RADIO_SIZE + 3.5, y: cy + 1.6, size: SIZE_SMALL + 0.4,
        font: this.fonts.regular, color: INK,
      });
      if (oneLine) cx += widths[i] + gap;
    }
    return { height: oneLine ? RADIO_SIZE : RADIO_SIZE + (choices.length - 1) * (RADIO_SIZE + 4) };
  }

  /** A signature rule with a typed-name field above it. */
  signatureWidget(entry, x, y, width) {
    const h = 26;
    this.textWidget(entry, { x, y: y - h + 8, width, height: h - 8 });
    this.page.drawLine({
      start: { x, y: y - h + 4 }, end: { x: x + width, y: y - h + 4 },
      thickness: 0.7, color: SECONDARY,
    });
    return { height: h };
  }
}

/** /TU is the accessible tooltip: what a screen reader announces for a field. */
function setTooltip(field, text) {
  if (!text) return;
  try {
    field.acroField.dict.set(PDFName.of('TU'), PDFString.of(toWinAnsi(String(text)).slice(0, 200)));
  } catch (_) { /* a tooltip is a nicety, never a reason to fail generation */ }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Block rendering
// ─────────────────────────────────────────────────────────────────────────────

const HEADING_STYLE = {
  0: { size: SIZE_TITLE, color: PRIMARY, bold: true, before: 4, after: 8 },
  1: { size: SIZE_H1, color: PRIMARY, bold: true, before: 13, after: 5 },
  2: { size: SIZE_H2, color: PRIMARY, bold: true, before: 10, after: 4 },
  3: { size: SIZE_H3, color: SECONDARY, bold: true, before: 8, after: 3 },
  4: { size: SIZE_BODY, color: SECONDARY, bold: true, before: 6, after: 2 },
};

function renderBlocks(flow, blocks, opts) {
  for (let i = 0; i < blocks.length; i += 1) {
    const block = blocks[i];
    switch (block.type) {
      case 'spacer':
        flow.y -= 5;
        break;
      case 'heading':
        renderHeading(flow, block, blocks[i + 1]);
        break;
      case 'paragraph':
        renderParagraph(flow, block, opts);
        break;
      case 'list':
        renderList(flow, block, opts);
        break;
      case 'table':
        renderTable(flow, block, opts);
        break;
      default:
        break;
    }
  }
}

/**
 * A heading is never the last thing on a page.
 *
 * Room is reserved for the heading AND the first line or two of whatever
 * follows it, so the break lands above the heading rather than immediately
 * below. Same rule as opal-document-builder.js, for the same reason: a clause
 * title stranded at the foot of a page reads as a clause with no content.
 */
function renderHeading(flow, block, next) {
  const st = HEADING_STYLE[block.level] || HEADING_STYLE[3];
  flow.y -= st.before;

  let follow = 24;
  if (next) {
    if (next.type === 'paragraph' || next.type === 'list') follow = LINE_BODY * 2;
    else if (next.type === 'table') follow = 34;
  }
  const lines = wrap(block.text, flow.fonts.bold, st.size, CONTENT_W - TEXT_SAFETY).length;
  flow.ensure(lines * st.size * 1.25 + follow);

  flow.text(block.text, {
    font: flow.fonts.bold, size: st.size, color: st.color, leading: st.size * 1.25,
  });
  flow.y -= st.after;
}

function renderParagraph(flow, block, opts) {
  const fields = block.runs.filter((r) => r.type === 'field');
  const text = block.runs.filter((r) => r.type === 'text').map((r) => r.text).join('').trim();

  const size = block.small ? SIZE_SMALL : SIZE_BODY;
  const font = block.emphasis ? flow.fonts.bold : flow.fonts.regular;
  const color = block.small ? SECONDARY : INK;

  if (text) {
    flow.text(text, { font, size, color, leading: block.small ? 9.6 : LINE_BODY });
  }
  // A field in running prose is given its own labelled row beneath the text.
  // Trying to sit a widget on the baseline mid-sentence produces a box that
  // overlaps the words on either side at any font size a viewer chooses.
  for (const f of fields) {
    renderStandaloneField(flow, f, opts);
  }
  flow.y -= 2.5;
}

function renderList(flow, block, opts) {
  const bullet = block.ordered ? '' : '•  ';
  const indent = 14;
  const text = block.runs.filter((r) => r.type === 'text').map((r) => r.text).join('').trim();
  if (text) {
    const lines = wrap(bullet + text, flow.fonts.regular, SIZE_BODY, CONTENT_W - indent - TEXT_SAFETY);
    for (let i = 0; i < lines.length; i += 1) {
      flow.ensure(LINE_BODY);
      flow.page.drawText(lines[i], {
        x: MARGIN_L + indent, y: flow.y - SIZE_BODY, size: SIZE_BODY,
        font: flow.fonts.regular, color: INK,
      });
      flow.y -= LINE_BODY;
    }
  }
  for (const f of block.runs.filter((r) => r.type === 'field')) {
    renderStandaloneField(flow, f, opts);
  }
  flow.y -= 1.5;
}

/** A field outside a table: a prompt label, then the widget. */
function renderStandaloneField(flow, entry, opts) {
  const readOnly = isLocked(entry, opts);
  const labelH = 10;
  const bodyH = fieldHeight(entry);

  flow.ensure(labelH + bodyH + 6);

  flow.page.drawText(toWinAnsi(entry.prompt), {
    x: MARGIN_L, y: flow.y - SIZE_SMALL, size: SIZE_SMALL,
    font: flow.fonts.regular, color: SECONDARY,
  });
  flow.y -= labelH;

  placeWidget(flow, entry, MARGIN_L, flow.y, CONTENT_W, bodyH, readOnly);
  flow.y -= bodyH + 5;
}

function fieldHeight(entry) {
  if (entry.kind === map.KIND.MULTILINE) return LINE_FIELD * 3 + FIELD_VPAD * 2;
  if (entry.kind === map.KIND.SIGNATURE) return 26;
  if (entry.kind === map.KIND.CHOICE) return RADIO_SIZE + 3;
  return MIN_FIELD_H;
}

/** Place one widget of the right type. `y` is the TOP of the box. */
function placeWidget(flow, entry, x, y, width, height, readOnly) {
  if (entry.kind === map.KIND.CHOICE && entry.choices && entry.choices.length) {
    return flow.radioWidget(entry, x, y - height + 1, width);
  }
  if (entry.kind === map.KIND.SIGNATURE) {
    return flow.signatureWidget(entry, x, y, width);
  }
  return flow.textWidget(
    entry,
    { x, y: y - height, width, height },
    { multiline: entry.kind === map.KIND.MULTILINE, readOnly }
  );
}

/**
 * Is this field locked in the issued document?
 *
 * Once an agreement is ISSUED, the provider's own entries are settled: a
 * participant must not be able to retype the rate, the support description or
 * the provider's signatory. What stays open is exactly the set the template
 * map marks participantEditable, plus the signature block. Anything else is
 * read-only, so the fillable PDF cannot become a route for renegotiating the
 * price after the fact.
 *
 * In manual mode nothing is locked: that document exists precisely so somebody
 * can complete the whole thing by hand.
 */
function isLocked(entry, opts) {
  if (!opts || !opts.lockProviderFields) return false;
  return !entry.participantEditable;
}

// ── Tables ───────────────────────────────────────────────────────────────────

function renderTable(flow, block, opts) {
  const rows = block.rows;
  const cols = Math.max(...rows.map((r) => r.cells.length));
  if (!cols) return;

  // Even columns, except a two-column row which is almost always a
  // label/value pair in this template and reads far better at 36/64.
  const widths = cols === 2
    ? [CONTENT_W * 0.36, CONTENT_W * 0.64]
    : new Array(cols).fill(CONTENT_W / cols);

  flow.y -= 3;

  for (const row of rows) {
    const measured = measureRow(flow, row, widths, cols);
    // A row is kept whole. Half a support's rate on one page and half on the
    // next is a price a participant can misread.
    flow.ensure(measured.height);
    drawRow(flow, row, widths, cols, measured, opts);
  }
  flow.y -= 5;
}

function measureRow(flow, row, widths, cols) {
  const cellLines = [];
  let maxH = 0;

  for (let c = 0; c < cols; c += 1) {
    const cell = row.cells[c];
    const inner = widths[c] - CELL_PAD * 2;
    const font = row.header ? flow.fonts.bold : flow.fonts.regular;

    const parts = [];
    let h = CELL_PAD * 2;
    if (!cell) { cellLines.push({ parts, height: h }); continue; }

    for (const runs of cell.paragraphs) {
      const text = runs.filter((r) => r.type === 'text').map((r) => r.text).join('').trim();
      const fields = runs.filter((r) => r.type === 'field');
      if (text) {
        const lines = wrap(text, font, SIZE_TABLE, inner - 2);
        parts.push({ kind: 'text', lines });
        h += lines.length * LINE_TABLE;
      }
      // A cell holding SEVERAL fields captions each one. With a single field
      // the neighbouring cell is the label — "PRIVACY | [field]" needs no
      // repetition — but two unlabelled boxes stacked in one cell are two
      // questions a reader has to guess at.
      const caption = fields.length > 1;
      for (const f of fields) {
        const fh = cellFieldHeight(f, inner, flow);
        parts.push({ kind: 'field', entry: f, height: fh, caption });
        h += fh + 2 + (caption ? 9 : 0);
      }
    }
    cellLines.push({ parts, height: h });
    maxH = Math.max(maxH, h);
  }

  return { cells: cellLines, height: Math.max(maxH, LINE_TABLE + CELL_PAD * 2) };
}

function cellFieldHeight(entry, innerWidth, flow) {
  if (entry.kind === map.KIND.MULTILINE) return LINE_FIELD * 2 + FIELD_VPAD * 2;
  if (entry.kind === map.KIND.SIGNATURE) return 24;
  if (entry.kind === map.KIND.CHOICE && entry.choices) {
    const gap = 9;
    const total = entry.choices.reduce((a, c) => a + RADIO_SIZE + 3.5
      + flow.fonts.regular.widthOfTextAtSize(toWinAnsi(c), SIZE_SMALL), 0)
      + gap * (entry.choices.length - 1);
    return total <= innerWidth
      ? RADIO_SIZE + 2
      : RADIO_SIZE + (entry.choices.length - 1) * (RADIO_SIZE + 4) + 2;
  }
  return MIN_FIELD_H;
}

function drawRow(flow, row, widths, cols, measured, opts) {
  const top = flow.y;
  const h = measured.height;

  let x = MARGIN_L;
  for (let c = 0; c < cols; c += 1) {
    flow.page.drawRectangle({
      x, y: top - h, width: widths[c], height: h,
      color: row.header ? SOFT_MINT : (row.supportRow ? WARM_NEUTRAL : WHITE),
      borderColor: BORDER, borderWidth: 0.5,
    });

    const inner = widths[c] - CELL_PAD * 2;
    let cy = top - CELL_PAD;
    const parts = (measured.cells[c] || {}).parts || [];

    for (const part of parts) {
      if (part.kind === 'text') {
        for (const line of part.lines) {
          if (line) {
            flow.page.drawText(line, {
              x: x + CELL_PAD, y: cy - SIZE_TABLE, size: SIZE_TABLE,
              font: row.header ? flow.fonts.bold : flow.fonts.regular,
              color: row.header ? PRIMARY : INK,
            });
          }
          cy -= LINE_TABLE;
        }
      } else {
        if (part.caption) {
          flow.page.drawText(toWinAnsi(part.entry.prompt).slice(0, 70), {
            x: x + CELL_PAD, y: cy - 6.4, size: 6.4,
            font: flow.fonts.regular, color: SECONDARY,
          });
          cy -= 9;
        }
        placeWidget(
          flow, part.entry, x + CELL_PAD, cy, inner, part.height,
          isLocked(part.entry, opts)
        );
        cy -= part.height + 2;
      }
    }
    x += widths[c];
  }

  flow.y = top - h;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Entry point
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @param {Buffer}  docxBuffer  the COMPOSED agreement .docx
 * @param {object}  meta        { reference, versionLabel, participantName,
 *                                statusLabel, generatedAt }
 * @param {boolean} lockProviderFields  true for an ISSUED agreement, false for
 *                  a manual blank form
 * @returns {Promise<{bytes: Buffer, pageCount, fieldCount, fieldNames, warnings}>}
 */
async function renderAgreementPdf({ docxBuffer, meta = {}, lockProviderFields = false }) {
  const outline = await outlineFromDocx(docxBuffer);

  const pdf = await PDFDocument.create();
  pdf.setTitle(`Service Agreement ${meta.reference || ''}`.trim());
  pdf.setAuthor('Opal Therapy');
  pdf.setSubject('NDIS Service Agreement');
  pdf.setProducer('Opal Therapy Portal');
  pdf.setCreator('Opal Therapy Portal');
  pdf.setLanguage('en-AU');

  const fonts = {
    regular: await pdf.embedFont(StandardFonts.Helvetica),
    bold: await pdf.embedFont(StandardFonts.HelveticaBold),
    italic: await pdf.embedFont(StandardFonts.HelveticaOblique),
  };

  const flow = new Flow(pdf, fonts, {
    headerLeft: 'NDIS SERVICE AGREEMENT',
    headerRight: meta.reference || '',
    footerLeft: [
      meta.participantName, meta.reference,
      meta.versionLabel ? `Template v${meta.versionLabel}` : null,
    ].filter(Boolean).join('  ·  '),
  });

  renderBlocks(flow, outline.blocks, { lockProviderFields });
  flow.finish();

  // Appearance streams AND NeedAppearances — see the file header for why both.
  try {
    flow.form.updateFieldAppearances(fonts.regular);
  } catch (err) {
    flow.warnings.push(`Field appearances could not be pre-generated: ${err.message}`);
  }
  flow.form.acroForm.dict.set(PDFName.of('NeedAppearances'), PDFBool.True);

  const bytes = Buffer.from(await pdf.save({ updateFieldAppearances: false }));

  return {
    bytes,
    pageCount: flow.pages.length,
    fieldCount: flow.form.getFields().length,
    fieldNames: flow.names.slice(),
    warnings: [...outline.warnings, ...flow.warnings],
  };
}

/** `Opal_Service_Agreement_<Participant>_<REF>.pdf` */
function agreementFilename(meta = {}, suffix = '') {
  const parts = ['Opal_Service_Agreement'];
  if (meta.participantName) parts.push(sanitiseFilenamePart(meta.participantName, 50));
  if (meta.reference) parts.push(sanitiseFilenamePart(meta.reference, 24));
  if (suffix) parts.push(sanitiseFilenamePart(suffix, 20));
  return `${parts.filter(Boolean).join('_')}.pdf`;
}

module.exports = {
  renderAgreementPdf,
  agreementFilename,
  // Exported so tests assert against the real numbers rather than copies.
  PAGE_W, PAGE_H, CONTENT_W, MARGIN_L, MEASURE_INSET, LINE_FIELD, SIZE_FIELD,
  _internals: { wrap, softenLongTokens, fieldName, fieldHeight, isLocked },
};
